#!/usr/bin/env python3
"""Phase 1.3 + 1.4: B형간염 + C형간염 — 5+5 each = 20 pages."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from gen_draft_pages import write_pages

# === Phase 1.3: B형간염 ===
HBV_HUB, HBV_LBL, HBV_SEC = "/B형간염/", "B형 간염", "B형 간염"

HBV = [
{"slug":"B형간염-Occult-잠복감염", "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"Occult HBV — HBsAg 음성·anti-HBc 양성", "h1":"Occult HBV(잠복 B형간염) — HBsAg 음성인데 DNA가 검출되는 상태",
"desc":"HBsAg 음성이지만 anti-HBc 양성, HBV DNA가 간세포·혈청에 잔존하는 occult HBV infection. 항암·면역억제 시 재활성화 위험과 평가 흐름.",
"keywords":"occult HBV, anti-HBc, 재활성화, 항암치료",
"tags":[("occult HBV",),("anti-HBc",),("재활성화",)],
"tldr":"<strong>Occult HBV infection</strong>은 혈청 HBsAg는 음성이지만 간 안의 cccDNA가 잠복해 있는 상태를 말합니다. 일반 검사로는 \"B형간염 회복\"으로 보이지만 면역억제·항암치료가 시작되면 다시 활성화될 수 있어 사전 평가가 중요합니다. Anti-HBc 양성 + HBV DNA 검출 시 진단되며, 한국 1세대(60대 이상)에서 비교적 흔합니다.",
"sections":[
{"heading":"진단 — 일반 검진에서는 잘 안 잡힘","html":"<p>일반 검진의 HBsAg만으로는 발견되지 않습니다. 진단의 단서는 다음 조합입니다.</p><ul><li><strong>HBsAg 음성 + anti-HBc 양성</strong> — 과거 노출 흔적. 그 자체로는 occult HBV 진단 아님.</li><li><strong>+ HBV DNA 검출(혈청 또는 간 조직)</strong> — occult HBV 확진. 혈청 DNA는 보통 매우 낮음(&lt; 200 IU/mL).</li><li>일부 환자는 anti-HBs도 양성(과거 자연 회복 패턴), 그래도 occult 상태 가능.</li></ul><p>가장 임상적으로 의미 있는 시점은 항암·면역억제 시작 전 평가입니다. HBsAg만 보고 안전하다고 단정하면 안 됩니다.</p>"},
{"heading":"재활성화 위험과 예방","html":"<p>면역억제·항암치료에서 occult HBV가 재활성화되어 \"reverse seroconversion\"(HBsAg 다시 양성으로) 일어나는 경우가 보고됩니다. 위험이 큰 상황:</p><ul><li><strong>Rituximab·anti-CD20</strong> — 가장 위험. 절대 예방 적응증.</li><li><strong>고용량 스테로이드 ≥ 4주, 항암화학요법</strong> — 중-고위험.</li><li><strong>장기이식 면역억제, 골수이식</strong> — 고위험.</li><li><strong>JAK 억제제·B세포 표적 약제</strong> — 위험.</li></ul><p>예방 — Entecavir 또는 TAF를 면역억제 시작 전 또는 동시에 시작, 면역억제 종료 후 최소 6~12개월(rituximab은 12~18개월) 지속.</p>"},
{"heading":"한국에서 occult HBV가 의미 있는 그룹","html":"<ul><li><strong>1세대(60대 이상) 출생자</strong> — 영아·소아 시절 B형간염 노출이 매우 흔했음. 일부가 자연 회복 후 잠복 상태.</li><li><strong>가족력 있는 환자</strong> — 어머니 보균자였던 환자가 자연 회복 후 잠복 가능.</li><li><strong>혈액암 환자</strong> — Rituximab·CHOP 등 사용 전 평가 필수.</li><li><strong>장기이식 수여자·기증자</strong> — anti-HBc 양성 기증자의 간을 받으면 occult HBV 전파 가능.</li></ul>"},
],
"faqs":[("HBsAg 음성인데 왜 B형간염 약을 먹어야 하나요?","Occult HBV는 일반 검사로는 안전해 보여도 면역억제 시 다시 활성화되는 위험이 있습니다. 항암·이식·rituximab 같은 강한 면역억제 전이라면 예방 항바이러스제를 검토합니다."),
("Anti-HBc 양성이면 모두 occult HBV인가요?","아닙니다. anti-HBc 단독 양성의 대부분은 자연 회복 후 anti-HBs가 시간이 지나며 떨어진 상태입니다. HBV DNA를 추가로 봐야 occult 여부가 결정됩니다."),
("Occult HBV 환자도 평생 항바이러스제를 먹어야 하나요?","아닙니다. 일반적인 상황에서는 정기 추적만 합니다. 면역억제·항암 시작 시점에만 예방 항바이러스제를 사용하고, 면역억제 종료 후 일정 기간 후 중단합니다.")],
"refs":["Raimondo G, et al. Update of the statement on occult hepatitis B virus infection. <em>J Hepatol</em> 2019.","Hwang JP, et al. Hepatitis B virus screening for patients with cancer before therapy: ASCO Provisional Clinical Opinion update. <em>J Clin Oncol</em> 2020."]},

{"slug":"B형간염-소아청소년-치료", "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"소아·청소년 B형간염", "h1":"소아·청소년 B형간염 — 치료 시점과 약물 선택",
"desc":"소아·청소년 만성 B형간염의 자연사 — 면역관용기에서 면역활동기로의 전환, 치료 적응증, 약물 선택(entecavir·TAF)과 장기 안전성.",
"keywords":"소아 B형간염, 청소년, entecavir, TAF, 면역관용기",
"tags":[("소아 B형간염",),("청소년",),("entecavir",)],
"tldr":"한국에서 신생아 B형간염 백신이 표준화되기 전(1995년 이전) 어머니에서 수직 감염된 환자가 소아·청소년기에 만성 보균자 상태로 진단되는 경우가 아직 있습니다. 대부분은 <strong>면역관용기</strong>로 HBeAg 양성, 매우 높은 HBV DNA, ALT 정상 패턴이라 즉시 치료 대상은 아닙니다. 면역활동기로 전환되어 ALT가 의미 있게 오르면 치료를 시작하며, 약물은 entecavir 또는 TAF가 표준입니다.",
"sections":[
{"heading":"자연사 — 4단계","html":"<ol><li><strong>면역관용기</strong> (소아·청소년기 흔함) — HBeAg+, DNA 매우 높음, ALT 정상. 면역계가 바이러스를 \"무시\"하는 시기. 즉시 치료 권장 안 됨.</li><li><strong>면역활동기(HBeAg+)</strong> — ALT 상승, 간 손상 시작. 치료 적응증.</li><li><strong>비활동성 보균기(HBeAg-)</strong> — HBeAg 음성, DNA 낮음, ALT 정상. 정기 추적.</li><li><strong>HBeAg- 활동기</strong> — Precore mutant. 다시 ALT 상승, 치료 적응증.</li></ol>"},
{"heading":"치료 적응증과 약물","html":"<ul><li>ALT 정상 상한 2배 이상 + 의미 있는 DNA, 또는 의미 있는 섬유화·간염 활성도</li><li>한국 식약처 적응증: entecavir 2세 이상, TAF 12세 이상, TDF 12세 이상</li><li>장기 안전성·골밀도·신기능 모니터 필수. 성장기에서 TAF가 골밀도·신기능 면에서 유리</li></ul>"},
{"heading":"한국 진료 현장","html":"<ul><li>학교 신체검사·헌혈에서 우연 발견되는 경우가 흔함</li><li>심리·가족 상담 중요 — 청소년기에 \"평생약\"이라는 압박, 학교생활·결혼 미래에 대한 걱정</li><li>가족 검사 — 어머니뿐 아니라 형제자매 모두 평가. 미접종 자녀에게 백신.</li></ul>"},
],
"faqs":[("소아인데 바로 약을 시작해야 하나요?","대부분 면역관용기라 즉시 치료 권장 안 됩니다. 정기 추적(3~6개월 ALT, 1년 영상)으로 활동기 전환을 감시합니다."),
("청소년 환자도 평생 약을 먹어야 하나요?","활동기에 진입해 약 시작하면 보통 장기 복용입니다. 일부에서 HBeAg 혈청전환·HBsAg 소실 도달 시 중단 검토 가능."),
("학교에서 차별을 받지 않을까요?","법적으로 일반 학교생활·체육 활동에 제한이 없습니다. 일상 접촉으로 거의 전염되지 않습니다. 학교 보건실과 상의하면 적절한 안내를 받을 수 있습니다.")],
"refs":["KASL Korean Pediatric Hepatology Guideline.","Sokal EM, et al. Management of chronic hepatitis B in childhood. <em>J Hepatol</em> 2013."]},

{"slug":"B형간염-D형간염-HDV", "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"D형간염(HDV) 동반 감염", "h1":"D형간염(HDV) — B형간염에 동반될 때 가장 빠른 간경변 원인",
"desc":"HBV에 의존하는 HDV. 동시 감염 vs 중복 감염, 진단(anti-HDV, HDV RNA), 신약 bulevirtide의 등장.",
"keywords":"HDV, D형간염, bulevirtide, 동반감염",
"tags":[("HDV",),("D형간염",),("bulevirtide",)],
"tldr":"<strong>D형간염 바이러스(HDV)</strong>는 B형간염 바이러스 표면 항원(HBsAg)을 이용해야만 복제할 수 있는 \"위성 바이러스\"입니다. B형간염에 동반될 때 가장 빠른 간경변 진행 원인이 되어 5~10년 내 약 70%가 간경변으로 갑니다. 한국에서는 드물지만 동남아·아프리카·중동 출신 환자 또는 정맥주사 약물 사용 이력이 있는 환자에서 검토합니다. 최근 EU에서 bulevirtide가 첫 HDV 표적 치료로 승인되었습니다.",
"sections":[
{"heading":"HDV의 특징","html":"<ul><li><strong>HBV 의존</strong> — HBV 없이 단독으로 존재할 수 없음. HBsAg 음성이면 HDV도 사라짐.</li><li><strong>전 세계 약 1,200만 명 추정</strong>. 한국은 매우 드묾(추정 유병률 0.1% 미만).</li><li><strong>고위험군</strong> — 정맥주사 약물 사용자, 동남아·아프리카·중동 출신, HIV 동반.</li><li><strong>가장 빠른 간경변 진행</strong> — HBV+HDV 동반은 HBV 단독보다 3~5배 빠른 진행.</li></ul>"},
{"heading":"진단 — HBsAg 양성 환자에서 한 번은 검사","html":"<ul><li><strong>Anti-HDV (IgG)</strong> — 노출 확인. 고위험군 HBsAg 양성 환자에서 검사.</li><li><strong>Anti-HDV (+) → HDV RNA</strong> — 활동성 감염 확인.</li><li>EASL 2023 가이드라인은 모든 HBsAg 양성 환자에서 anti-HDV 한 번 검사 권고. 한국 임상 적용은 의료기관·환자 위험에 따라.</li></ul>"},
{"heading":"치료 — 신약 시대 개막","html":"<ul><li><strong>Pegylated interferon alpha</strong> — 전통적. 48주, 반응률 약 25%, 부작용 큼.</li><li><strong>Bulevirtide(EU 2020 승인)</strong> — HDV가 간세포 진입에 사용하는 NTCP 수용체 차단. 매일 피하 주사. 미국·한국 미승인(2026년 5월 기준 임상시험 단계).</li><li><strong>Lonafarnib</strong> — Farnesyltransferase 억제. 임상시험 단계.</li><li>HBV 항바이러스제(entecavir·TAF)는 HDV에 직접 효과 없으나 HBV 억제로 간접 효과 일부.</li></ul>"},
],
"faqs":[("한국에서 D형간염은 흔한가요?","매우 드뭅니다. 일반 인구 유병률 0.1% 미만. 다만 일부 고위험군(외국 출생, 정맥주사 이력)에서는 한 번 검사 가치 있습니다."),
("B형간염 검사에서 D형간염도 같이 나오나요?","아닙니다. anti-HDV는 별도 검사로 진료의가 의심해야 시행됩니다. HBsAg 양성 + 빠른 간 손상이면 한 번 검사 검토."),
("Bulevirtide는 한국에서 받을 수 있나요?","2026년 5월 현재 한국 미승인. 임상시험 또는 임시 도입 절차를 통한 사용을 의료기관에 문의 가능.")],
"refs":["Wedemeyer H, et al. A phase 3, randomized trial of bulevirtide in chronic hepatitis D. <em>NEJM</em> 2023.","Negro F. Hepatitis D virus coinfection and superinfection. <em>Cold Spring Harb Perspect Med</em> 2014."]},

{"slug":"B형간염-신기능-약물선택", "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"신기능 저하 환자의 항바이러스제", "h1":"신기능이 떨어진 B형간염 환자의 항바이러스제 선택 — TDF vs TAF vs ETV",
"desc":"CKD·투석 환자의 B형간염 치료 — 신독성을 줄이는 TAF·entecavir 선호. 용량 조정 기준과 TDF에서 TAF로 전환 시점.",
"keywords":"신기능, CKD, 투석, TAF, entecavir",
"tags":[("CKD",),("TAF",),("entecavir",),("신기능",)],
"tldr":"TDF는 장기 사용 시 신독성·골밀도 감소 부작용이 있어 신기능이 떨어진 환자에서 우선 회피합니다. <strong>Entecavir 또는 TAF</strong>가 신기능·골밀도 측면에서 안전한 옵션이며 한국에서도 신기능 저하 환자에서 TAF로의 전환이 표준이 되었습니다. CrCl 15 미만·투석 환자에서는 용량 조정이 필요합니다.",
"sections":[
{"heading":"각 약물의 신기능 영향","html":"<table><thead><tr><th>약물</th><th>신독성</th><th>골밀도</th><th>비고</th></tr></thead><tbody><tr><td>TDF</td><td>장기 사용 시 의미 있음 (Fanconi 양상)</td><td>감소</td><td>신기능 안 좋은 환자에서 우선 회피</td></tr><tr><td>TAF</td><td>매우 적음</td><td>거의 영향 없음</td><td>신기능·골밀도 우려 환자 1차</td></tr><tr><td>Entecavir</td><td>거의 없음</td><td>거의 없음</td><td>표준 옵션, CrCl 따라 용량 조정</td></tr></tbody></table>"},
{"heading":"전환 시점","html":"<ul><li>CrCl &lt; 60 또는 진행 패턴 — TAF 또는 entecavir로 전환 검토</li><li>골다공증·골절 위험 — TAF가 안전</li><li>당뇨·고혈압 동반 — 신기능 추적 강화, 6개월 간격 CrCl·인·칼슘</li></ul>"},
{"heading":"투석 환자","html":"<p>혈액투석 환자에서는 entecavir 또는 TAF 모두 사용 가능. Entecavir는 신기능에 따라 용량을 줄이고(예: 격일 0.5 mg), 투석 후 복용. TAF는 신기능과 무관하게 25 mg/일 표준 용량 유지 가능(투석 후 복용). 신장이식 후에는 면역억제 중 재활성화 위험으로 평생 예방 필요.</p>"},
],
"faqs":[("CrCl이 50인데 TDF에서 TAF로 바꿔야 하나요?","장기 TDF 사용 중이라면 전환을 권합니다. TAF가 신기능 보호에 유리하며 항바이러스 효과는 동등합니다."),
("투석 중인데 약 시간을 어떻게 맞추나요?","투석 후 복용이 일반적입니다. 투석 중 약물이 일부 제거되기 때문에 투석 전 복용은 효과 감소 가능성이 있습니다."),
("신장이식 후에도 B형간염 약을 먹어야 하나요?","네, 평생 사용이 표준입니다. 면역억제로 재활성화 위험이 매우 큽니다.")],
"refs":["KASL 만성 B형간염 가이드라인.","Marcellin P, et al. Tenofovir alafenamide versus tenofovir disoproxil fumarate in chronic HBV. <em>Lancet Gastroenterol Hepatol</em> 2016."]},

{"slug":"B형간염-수술전-예방", "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"수술·시술 전 B형간염 예방", "h1":"수술·시술 전 B형간염 평가와 예방 항바이러스제",
"desc":"비활동성 B형간염 보균자가 큰 수술·면역억제 시술을 앞두고 있을 때 단기 예방 항바이러스제 사용. 어떤 환자·시술에서 권장되나.",
"keywords":"수술전평가, 예방, 면역억제, 재활성화",
"tags":[("수술전평가",),("예방",),("재활성화",)],
"tldr":"비활동성 B형간염 보균자(HBsAg+·ALT 정상·낮은 DNA)도 면역억제·항암·큰 수술 후 재활성화 위험이 있습니다. <strong>Rituximab, 고용량 스테로이드, 항암화학요법, 장기이식 면역억제</strong>가 가장 큰 위험. 시술 시작 1주 전 또는 동시에 entecavir/TAF 시작 후 면역억제 종료 6~12개월(rituximab은 12~18개월) 지속이 표준입니다.",
"sections":[
{"heading":"위험 단계 분류","html":"<table><thead><tr><th>위험</th><th>약/시술</th><th>권고</th></tr></thead><tbody><tr><td>고위험 (&gt;10%)</td><td>Rituximab, 골수이식, 고용량 스테로이드 ≥ 4주</td><td>예방 항바이러스제 필수</td></tr><tr><td>중위험 (1-10%)</td><td>항암화학요법, anti-TNF, JAK 억제제</td><td>예방 권장</td></tr><tr><td>저위험 (&lt;1%)</td><td>짧은 스테로이드, MTX, 일반 수술</td><td>모니터, 재활성화 시 즉시 약</td></tr></tbody></table>"},
{"heading":"평가 흐름","html":"<ol><li>모든 면역억제 전 환자에서 HBsAg + anti-HBc + anti-HBs 검사</li><li>HBsAg 양성이면 위험 단계에 따라 예방 결정</li><li>HBsAg 음성·anti-HBc 양성(occult 가능)이면 위험 약 사용 시 예방 검토</li><li>HBV DNA 베이스라인 측정</li></ol>"},
{"heading":"한국 진료","html":"<ul><li>혈액내과·종양내과·류마티스과에서 면역억제 시작 전 자동으로 간내과 협진 의뢰가 이루어지는 의료기관 늘고 있음</li><li>예방 약 시작 누락은 가장 흔한 실수 — 시술 시작 후 발견되어도 즉시 시작이 표준</li><li>예방 종료 시점이 환자별로 다름. Rituximab은 종료 후 12~18개월 지속, 일반 항암은 6개월 이상.</li></ul>"},
],
"faqs":[("일반 수술(예: 담낭절제) 전에도 약을 먹어야 하나요?","비활동성 보균자에서 짧은 마취·수술 자체는 재활성화 위험이 매우 낮아 보통 예방 약은 필요 없습니다. 술기 중 스테로이드·면역억제 약을 길게 쓰는 경우만 검토."),
("이미 항암 시작했는데 B형간염을 발견했어요","즉시 항바이러스제 시작 + ALT·DNA 추적. 늦지 않게 시작하면 대부분 안전하게 관리됩니다."),
("예방 약을 언제까지 먹어야 하나요?","면역억제 종료 후 6~12개월(rituximab은 12~18개월) 지속이 표준입니다. 종료 후 ALT·DNA 추적으로 안정 확인 후 중단.")],
"refs":["Hwang JP, et al. Hepatitis B virus screening before therapy: ASCO update. <em>J Clin Oncol</em> 2020.","Loomba R, Liang TJ. Hepatitis B reactivation associated with immune suppressive and biological modifier therapies. <em>Gastroenterology</em> 2017."]},

# === Cases for HBV ===
{"slug":"B형간염-Occult-항암치료", "is_case":True, "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"림프종 항암 전 occult HBV 발견", "h1":"R-CHOP 시작 전 anti-HBc 양성 발견 — Occult HBV로 예방 시작",
"desc":"DLBCL 진단 환자에서 R-CHOP 시작 전 HBsAg 음성이지만 anti-HBc 양성 발견. HBV DNA 검사로 occult HBV 진단 후 entecavir 예방.",
"keywords":"occult HBV, rituximab, 예방",
"tags":[("occult HBV",),("rituximab",),("예방",)],
"case_intro":"68세 남성. 미만성 거대 B 세포 림프종(DLBCL) 진단으로 R-CHOP 시작 예정. 사전 검사에서 HBsAg 음성, anti-HBs 양성(120 mIU/mL), anti-HBc 양성. HBV DNA 추가 측정에서 80 IU/mL로 검출.",
"sections":[
{"heading":"평가","html":"<p>Anti-HBc 양성 + HBV DNA 검출 = occult HBV로 진단. R-CHOP은 rituximab 포함 — 재활성화 고위험.</p>"},
{"heading":"예방 결정","html":"<p>혈액내과·간내과 협진. Entecavir 0.5 mg/일 R-CHOP 첫 사이클 1주 전 시작. R-CHOP 8 사이클 완료, 추가 12개월 entecavir 지속(총 약 20개월). 항암 중 정기 ALT·HBV DNA 모니터 — 모두 정상 유지.</p>"},
],
"teaching":["<strong>Rituximab은 재활성화 최고위험</strong>. anti-HBc 양성만으로도 예방 적응증.","<strong>Anti-HBs 양성이라도 안전 보장 안 됨</strong> — occult HBV에서 재활성화 보고됨.","<strong>예방 시작 시점</strong> — 항암 시작 1주 전 또는 같이 시작 (가능하면 1주 전 우선).","<strong>예방 종료</strong> — Rituximab은 마지막 투여 후 12~18개월. 종료 후 ALT·DNA 추적.","<strong>혈액내과 처방 시 자동 협진 체계가 안전 마진</strong> — 한국 대형 병원 점차 표준화."],
},
{"slug":"B형간염-신기능저하-TAF전환", "is_case":True, "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"TDF 10년 후 CrCl 저하 — TAF 전환", "h1":"TDF 10년 복용 환자의 CrCl 55 — TAF 전환 결정",
"desc":"고혈압·당뇨 동반 B형간염 환자에서 TDF 10년 사용 중 CrCl이 점진 저하. TAF로 전환 후 신기능 안정·항바이러스 효과 유지.",
"keywords":"TDF, TAF, 신기능, 전환",
"tags":[("TDF",),("TAF",),("신기능",)],
"case_intro":"63세 남성. 만성 B형간염, 고혈압·당뇨 동반. TDF 300 mg/일 10년 복용. 매년 추적에서 CrCl 점진 감소(85 → 72 → 65 → 58 → 55). HBV DNA 검출 한계 이하 유지.",
"sections":[
{"heading":"평가와 결정","html":"<p>TDF의 장기 신독성 의심 — 약물 외 다른 신기능 영향 인자(당뇨·고혈압) 확인. 단백뇨 미경증 양성. TAF로의 전환 결정.</p>"},
{"heading":"경과","html":"<p>TAF 25 mg/일로 전환. 전환 후 6개월 — CrCl 60으로 약간 회복, 단백뇨 음성. HBV DNA 검출 한계 이하 유지. 골밀도 추적에서도 안정. 12개월 시점 CrCl 62 유지.</p>"},
],
"teaching":["<strong>장기 TDF 사용 환자의 CrCl 60 이하 또는 진행성 저하 — TAF 전환 검토</strong>","<strong>전환은 동등한 항바이러스 효과 유지</strong> + 신기능·골밀도 보호","<strong>당뇨·고혈압 동반 환자는 TDF 신독성에 더 취약</strong>","<strong>전환 후 6~12개월 신기능 추적</strong> — 약물 외 다른 원인이 있다면 그쪽도 함께 관리","<strong>골다공증 위험 환자도 TAF 우선</strong>"],
},
{"slug":"B형간염-HDV-동반", "is_case":True, "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"빠른 간경변 진행 환자에서 HDV 발견", "h1":"5년 만에 간경변으로 진행한 30대 환자 — Anti-HDV 양성",
"desc":"30대 남성에서 만성 B형간염 진단 5년 만에 비대상성 간경변으로 빠르게 진행. Anti-HDV 검사에서 HDV 동반 감염 발견 사례.",
"keywords":"HDV, 빠른진행, 간경변",
"tags":[("HDV",),("빠른진행",)],
"case_intro":"32세 남성, 외국(동남아) 거주 이력. 5년 전 만성 B형간염 진단 시 ALT 80, DNA 10⁵, HBeAg 양성. Entecavir 시작 후 HBV DNA 검출 한계 이하, ALT 정상화. 그러나 ALT가 다시 오르고 빠르게 간경변·복수 진행. 진료의가 비전형적 진행 패턴으로 anti-HDV 추가 검사.",
"sections":[
{"heading":"진단","html":"<p>Anti-HDV IgG 양성, HDV RNA 검출. HBV는 entecavir로 잘 억제되어 있으나 HDV로 인한 간 손상이 지속된 것으로 해석. 환자는 동남아 거주 시기에 HDV 노출 가능성.</p>"},
{"heading":"치료와 경과","html":"<p>Pegylated interferon alpha 48주 치료 시도 — 부작용으로 6개월에 중단. HDV RNA 일시 감소했으나 후 다시 상승. Bulevirtide 한국 미승인이라 임상시험 참여 검토 중. 비대상성 간경변 → 간이식 평가 시작.</p>"},
],
"teaching":["<strong>비전형적으로 빠른 진행 — HDV 검사 검토</strong>. HBV 잘 억제되는데 간 손상이 계속되면 단서.","<strong>외국 거주 이력·정맥주사 이력·HIV 동반 — HDV 위험군</strong>","<strong>EASL 2023은 모든 HBsAg+ 환자 1회 anti-HDV 권고</strong>","<strong>치료 옵션이 제한적</strong> — Pegylated interferon, bulevirtide(EU 승인). 임상시험 적극 검토.","<strong>비대상성으로 진행하면 이식 평가</strong>"],
},
{"slug":"B형간염-소아청소년-치료시작", "is_case":True, "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"16세 청소년의 면역활동기 진입", "h1":"16세 만성 B형간염 환자의 면역활동기 진입 — Entecavir 시작",
"desc":"신생아부터 보균 상태였던 16세 학생에서 ALT가 오르며 면역활동기 진입. 가족·학교 상담 후 entecavir 시작 사례.",
"keywords":"소아 B형간염, 청소년, 면역활동기",
"tags":[("소아 B형간염",),("청소년",)],
"case_intro":"16세 여학생. 어머니가 B형간염 보균자로 출생 시 HBIG·백신 받지 못한 환자. 신생아부터 만성 보균 상태로 면역관용기로 추적 중(HBeAg+, DNA 10⁸, ALT 정상). 이번 정기 검사에서 ALT 120, AST 95로 처음으로 상승.",
"sections":[
{"heading":"평가","html":"<p>면역활동기 진입 — ALT 정상 상한의 2.5배 이상, HBeAg 양성 + 높은 DNA. 6주 후 재검에서도 ALT 105 — 일과성 아니고 지속. 영상에서 경증 간 비대, Fibroscan 7.5 kPa(경증 섬유화).</p>"},
{"heading":"치료 결정과 경과","html":"<p>식약처 적응증 entecavir 0.5 mg/일 시작(2세 이상 사용 가능). 환자·부모와 함께 \"평생약\" 개념·중단 시점·학교생활 상담. 6개월 후 ALT 정상화, DNA 10³로 감소. HBeAg는 아직 양성.</p>"},
],
"teaching":["<strong>소아·청소년 면역관용기는 보통 치료 대상 아님</strong>. 면역활동기 진입 신호인 ALT 상승은 추적의 핵심.","<strong>식약처 적응증 — entecavir 2세 이상</strong>","<strong>심리·가족 상담 중요</strong> — 청소년기에 \"평생약\" 압박, 미래 결혼·출산 걱정","<strong>학교·체육 활동 제한 없음</strong> — 일상 접촉으로 거의 전염 안 됨","<strong>가족·형제 검사 동시 평가</strong>"],
},
{"slug":"B형간염-수술전-예방", "is_case":True, "hub_path":HBV_HUB, "hub_label":HBV_LBL, "section":HBV_SEC,
"title":"신장이식 전 B형간염 예방", "h1":"신장이식 수여자의 비활동성 B형간염 — Entecavir 평생 예방",
"desc":"신장이식 대기 환자에서 비활동성 B형간염 보균 상태. 이식 1주 전 entecavir 시작 후 평생 유지하는 사례.",
"keywords":"신장이식, 예방, entecavir",
"tags":[("신장이식",),("예방",)],
"case_intro":"58세 여성. 당뇨병성 신증으로 혈액투석 중, 신장이식 대기자. 비활동성 B형간염 보균자(HBsAg+, HBeAg-, DNA 검출 한계 이하, ALT 정상). 이식 전 평가에서 평생 예방 필요로 결정.",
"sections":[
{"heading":"예방 결정","html":"<p>면역억제(타크롤리무스 + 마이코페놀레이트 + 스테로이드) 시작 후 재활성화 위험이 매우 큼. 이식 1주 전 <strong>entecavir 0.5 mg 격일</strong>(투석 환자 용량 조정) 시작. 이식 후 일반 용량으로 전환.</p>"},
{"heading":"경과","html":"<p>신장이식 후 1년 — 그래프트 기능 안정, B형간염 ALT·DNA 정상 유지. 면역억제제 + entecavir 동시 복용. 평생 entecavir 지속 계획.</p>"},
],
"teaching":["<strong>장기이식 + 평생 면역억제 — B형간염 평생 예방 표준</strong>","<strong>이식 전 시작이 우선</strong>. 가능하면 1주 전, 늦어도 이식 당일.","<strong>투석 환자 용량 조정 필요</strong> — entecavir 0.5 mg 격일 또는 신기능에 따라","<strong>이식 후 일반 용량 전환</strong> — 신장이식의 경우 새 신장 기능 안정 후","<strong>면역억제와의 상호작용 거의 없음</strong> — 안심하고 병용"],
},
]

# === Phase 1.4: C형간염 ===
HCV_HUB, HCV_LBL, HCV_SEC = "/C형간염/", "C형 간염", "C형 간염"

HCV = [
{"slug":"C형간염-재감염-위험군", "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"DAA 완치 후 재감염 위험", "h1":"DAA 완치 후 재감염 — 누가, 언제, 어떻게 추적하나",
"desc":"DAA로 완치(SVR) 후에도 재감염 가능. 위험 행동이 지속되는 환자(정맥주사 약물, 다파트너)의 1년 간격 RNA 추적과 재감염 시 재치료.",
"keywords":"재감염, DAA, 정맥주사, 위험행동",
"tags":[("재감염",),("DAA",),("위험행동",)],
"tldr":"DAA로 SVR12에 도달하면 영구 면역이 생기지 않습니다. 같은 또는 다른 genotype에 다시 감염될 수 있어 위험 행동이 지속되는 환자는 정기 RNA 추적이 필요합니다. 재감염률은 일반 인구에서는 매우 낮지만 정맥주사 약물 사용자에서 연 5~10%까지 보고됩니다. 재감염도 DAA로 재치료 가능합니다.",
"sections":[
{"heading":"누가 재감염 위험군인가","html":"<ul><li><strong>정맥주사 약물 사용자</strong> — 가장 큰 위험. 주삿바늘 공유.</li><li><strong>HIV 동반</strong> — 일부에서 성접촉 매개 HCV 재감염 보고.</li><li><strong>혈액투석 환자</strong> — 같은 의료기관 내 감염 통제 미비 시.</li><li><strong>의료진</strong> — 주삿바늘 자상 노출.</li><li><strong>일반 인구</strong> — 재감염 매우 드묾(연 0.1% 미만).</li></ul>"},
{"heading":"추적 일정","html":"<ul><li>위험군 — SVR12 후 1년마다 HCV RNA 1회</li><li>일반 인구 — 정기 RNA 추적 불필요</li><li>위험 행동 중단되면 추적 종료 검토</li><li>ALT 새 상승이 있으면 즉시 RNA 검사</li></ul>"},
{"heading":"재감염 시 재치료","html":"<p>재감염도 DAA로 치료 가능. SVR 도달률은 일반 환자와 비슷한 95% 이상. 다만 보험 적용은 의료기관·환자 상황에 따라 조정. 같은 genotype 재감염은 같은 약 다시 사용 가능, 다른 genotype 시 pangenotype DAA(글레카프레비르/피브렌타스비르 또는 소포스부비르/벨파타스비르) 선호.</p>"},
],
"faqs":[("DAA로 완치 후 헌혈할 수 있나요?","한국은 anti-HCV 양성 이력으로 평생 헌혈 불가입니다. RNA 음성 상태여도 마찬가지."),
("위험 행동을 다시 시작하면 어떻게 해야 하나요?","즉시 의료진과 상의. 노출 직후 RNA 검사가 가능합니다. 재감염 시 빠른 치료 시작이 만성화 예방에 효과적."),
("성접촉으로 재감염되나요?","모노가미 관계에서 재감염은 매우 드뭅니다. 다파트너·MSM에서는 위험이 일부 있어 위생적 성접촉이 안전.")],
"refs":["AASLD-IDSA HCV Guidance.","Midgard H, et al. HCV reinfection rates after successful treatment. <em>J Hepatol</em> 2016."]},

{"slug":"C형간염-신부전-치료", "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"신부전·투석 환자의 C형간염 치료", "h1":"CKD·혈액투석 환자의 C형간염 DAA 치료",
"desc":"CKD stage 4-5·투석 환자의 C형간염도 DAA로 완치 가능. 글레카프레비르/피브렌타스비르가 표준 1차, 8~12주 치료.",
"keywords":"CKD, 투석, DAA, 글레카프레비르",
"tags":[("CKD",),("투석",),("DAA",)],
"tldr":"신기능이 떨어진 C형간염 환자도 DAA로 SVR 95%+ 도달이 가능합니다. <strong>글레카프레비르/피브렌타스비르</strong>(maviret/마비렛)는 신기능과 무관하게 사용 가능한 pangenotype DAA로 신부전·투석 환자의 1차 옵션입니다. 소포스부비르 함유 제제는 CrCl &lt; 30에서 회피. 신장이식 대기·후 환자의 평가에서도 우선순위 높음.",
"sections":[
{"heading":"DAA 선택의 신기능 영향","html":"<table><thead><tr><th>약물</th><th>CrCl &lt; 30·투석</th></tr></thead><tbody><tr><td>글레카프레비르/피브렌타스비르</td><td>안전, 용량 조정 불필요. 1차.</td></tr><tr><td>엘바스비르/그라조프레비르</td><td>안전. 일부 사용.</td></tr><tr><td>소포스부비르/벨파타스비르</td><td>회피 권고 (소포스부비르 신배설)</td></tr><tr><td>소포스부비르/레디파스비르</td><td>회피 권고</td></tr></tbody></table>"},
{"heading":"치료 흐름","html":"<ul><li>HCV RNA 양성 확인 후 1차 평가</li><li>genotype·간섬유화·HBV·HIV 동반 평가</li><li>글레카프레비르/피브렌타스비르 8주(비간경변) 또는 12주(간경변)</li><li>SVR12 평가 — 신기능에 따른 추적 부담 고려해 외래 일정 조정</li></ul>"},
{"heading":"신장이식과의 관계","html":"<p>HCV 양성 환자도 신장이식 대기·수여 가능. DAA 시대에는 일부에서 \"HCV+ 기증자 신장 → HCV- 수여자\" 옵션도 검토됨(이식 후 즉시 DAA 치료로 SVR). 한국에서 표준은 아직 아니지만 미국·일부 EU에서 활발.</p>"},
],
"faqs":[("투석 중인데 DAA 받을 수 있나요?","네, 글레카프레비르/피브렌타스비르가 1차 옵션. 8주 치료, SVR 95%+."),
("신장이식 대기 중인데 C형간염 먼저 치료해야 하나요?","대부분 이식 전 DAA로 SVR 달성이 표준. 일부 의료기관에서는 이식 후 즉시 치료 옵션도 검토."),
("DAA 치료 중 신기능이 변하나요?","대부분 신기능에 영향 없습니다. 정기 추적은 유지.")],
"refs":["AASLD-IDSA HCV Guidance: HCV in patients with renal impairment.","Gane EJ, et al. Glecaprevir/pibrentasvir in patients with HCV and severe renal impairment (EXPEDITION-4). <em>NEJM</em> 2017."]},

{"slug":"C형간염-임신수유", "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"임신·수유와 C형간염", "h1":"임신 계획·중·수유 시 C형간염 — DAA 시점과 안전성",
"desc":"임신 전 DAA 완치가 표준. 임신 중 DAA는 충분한 안전성 자료 없어 대부분 출산 후 치료. 수유 중에는 일반적으로 안전.",
"keywords":"임신, 수유, DAA, 수직감염",
"tags":[("임신",),("수유",),("수직감염",)],
"tldr":"임신 계획이 있다면 임신 전 DAA로 SVR 도달이 표준입니다. 임신 중 DAA는 충분한 안전성 자료가 없어 일반적으로 출산 후로 미룹니다. HCV 수직감염률은 약 5~6%(HIV 동반 시 더 높음)로 B형간염보다 낮으나 0은 아니며, 자녀는 출생 18개월 후 anti-HCV 검사가 표준.",
"sections":[
{"heading":"임신 전","html":"<ul><li>임신 계획 6개월 전 DAA 완치 권장</li><li>완치 후 SVR12 확인 후 임신 진행이 안전</li><li>리바비린 함유 제제는 임신 전후 6개월 회피(태아 기형 위험)</li><li>HCV RNA 양성 채로 임신 계획 시 산과·간내과 협진</li></ul>"},
{"heading":"임신 중 발견 시","html":"<ul><li>대부분 출산 후 DAA 치료로 미룸</li><li>임신 중 DAA 사용은 case-by-case로 일부 의료기관에서 검토되나 표준 권고는 아님</li><li>임신 중 ALT 모니터, 간 기능 평가</li><li>분만 방식 — 일반 산과 적응증으로 결정 (제왕절개가 수직감염 줄이지 않음)</li></ul>"},
{"heading":"수유와 신생아","html":"<ul><li>모유 수유는 안전 (모유에 RNA 매우 낮음, 영아 감염 보고 없음)</li><li>유두 출혈 시 일시 중단 권고</li><li>출생 직후 영아 anti-HCV는 모체 항체로 위양성 — 18개월 후 anti-HCV 또는 6개월 후 RNA 검사 시 결정적</li></ul>"},
],
"faqs":[("DAA로 완치된 후 임신해도 되나요?","SVR12 확인 후 임신 가능. 리바비린을 썼다면 6개월 후."),
("임신 중에 발견됐는데 어떻게 하나요?","대부분 출산 후 치료로 미루고 정기 추적. 의료기관에 따라 임신 중 DAA 검토도 가능."),
("아이는 언제 검사하나요?","18개월 후 anti-HCV 또는 6개월 후 HCV RNA. 양성이면 추가 평가.")],
"refs":["AASLD-IDSA HCV Guidance: pregnancy.","Hughes BL, et al. Hepatitis C in pregnancy. <em>Obstet Gynecol</em> 2017."]},

{"slug":"C형간염-HIV-동반", "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"HIV·HCV 동반 감염", "h1":"HIV·HCV 동반 감염 — 동시 치료의 결정",
"desc":"HIV·HCV 동반 환자에서 DAA 치료. 항레트로바이러스제와의 약물 상호작용 평가, SVR 도달률은 HIV 단독 음성 환자와 동등.",
"keywords":"HIV, HCV, 동반감염, 약물상호작용",
"tags":[("HIV",),("HCV",),("동반감염",)],
"tldr":"HIV·HCV 동반 환자도 DAA로 SVR 95%+ 도달이 가능합니다. 핵심은 <strong>항레트로바이러스제와의 약물 상호작용</strong> 평가. 일부 단백분해효소 억제제(PI)는 DAA와 상호작용 강해 ART 조합 조정이 필요할 수 있습니다. 감염내과·간내과 협진이 표준.",
"sections":[
{"heading":"DAA 치료의 핵심 — 약물 상호작용","html":"<ul><li>글레카프레비르/피브렌타스비르 ↔ atazanavir·ritonavir·darunavir 등 PI 일부 — 금기 또는 신중</li><li>소포스부비르/벨파타스비르 ↔ amiodarone 함께 사용 시 brady 위험</li><li>NRTI(테노포비르·엠트리시타빈 등) — 일반적으로 안전</li><li>Integrase 억제제(dolutegravir·bictegravir) — 안전</li><li>리바미피드와는 무관, 일반 영양제 가능</li></ul>"},
{"heading":"치료 흐름","html":"<ul><li>감염내과 협진으로 ART 평가</li><li>필요 시 ART 조합 단기 조정(예: PI → integrase inhibitor)</li><li>DAA 8~12주</li><li>SVR12 확인 후 일반 추적</li></ul>"},
{"heading":"한국 진료","html":"<p>HIV·HCV 동반 환자는 한국에서 점차 늘고 있어 감염내과·간내과 협진 체계가 잡혀 있습니다. ART 조정·DAA 선택·약물 상호작용 평가는 보통 두 진료과가 함께 결정합니다.</p>"},
],
"faqs":[("HIV가 있어도 DAA로 완치되나요?","네, SVR 95%+로 단독 환자와 동등."),
("ART를 끊고 DAA 받아야 하나요?","아닙니다. ART 지속이 원칙. 다만 일부 PI는 DAA와 상호작용으로 ART 조정이 필요할 수 있음."),
("HIV·HCV 모두 RNA 음성이 가능한가요?","HCV는 완치 가능(SVR), HIV는 평생 ART로 RNA 검출 한계 이하 유지(완치 아닌 controlled).")],
"refs":["AASLD-IDSA HCV Guidance: HIV/HCV coinfection.","Sulkowski MS. Outcomes for patients coinfected with HCV and HIV. <em>NEJM</em> 2014."]},

{"slug":"C형간염-DAA-실패-재치료", "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"DAA 1차 실패 후 재치료", "h1":"DAA 1차 SVR 실패 — 재치료 옵션",
"desc":"첫 DAA 치료에서 SVR 도달 못한 환자(약 1~5%)의 재치료 — 소포스부비르/벨파타스비르/복실라프레비르(보세비) 12~24주 표준.",
"keywords":"DAA실패, 재치료, 보세비, 내성변이",
"tags":[("DAA실패",),("재치료",),("내성변이",)],
"tldr":"첫 DAA에서 SVR을 못 얻는 환자가 약 1~5%로 보고됩니다. 가장 흔한 원인은 약 복용 순응도 저하·약물 상호작용 누락·복용 중단입니다. 재치료의 표준은 <strong>소포스부비르/벨파타스비르/복실라프레비르(보세비, Vosevi)</strong> 12주(간경변 시 24주). 1차에서 발견되지 않은 약제 내성 변이(RAS) 평가가 도움됩니다.",
"sections":[
{"heading":"실패 원인 평가","html":"<ul><li>복용 순응도 — 빠뜨린 횟수·식사와 함께 복용 여부</li><li>약물 상호작용 — 한약·영양제·다른 처방약</li><li>알코올 동시 음용</li><li>약제 내성 변이(RAS) — NS5A 등 일부 검사 가능</li><li>재감염 가능성 — RNA 변화 패턴 확인</li></ul>"},
{"heading":"재치료","html":"<ul><li><strong>보세비(SOF/VEL/VOX) 12주</strong> — 가장 풍부한 자료. SVR 95%+.</li><li>간경변 동반 시 24주 검토</li><li>리바비린 추가는 일부 어려운 케이스에서</li><li>한국 보험 — 1차 실패 후 재치료 적응증 인정</li></ul>"},
{"heading":"환자 상담","html":"<p>첫 실패는 환자가 충격으로 받아들이는 경우가 많습니다. \"DAA 시대에 1~5%는 실패한다, 재치료로 거의 모두 완치 가능하다\"는 메시지를 분명히 전달합니다. 동시에 복용 패턴·다른 약·알코올 등을 함께 점검해 같은 실수 반복을 피합니다.</p>"},
],
"faqs":[("1차 실패가 영구 실패인가요?","아닙니다. 재치료로 95%+ SVR 도달 가능."),
("내성 검사가 꼭 필요한가요?","대부분 보세비 1차 재치료로 충분해 일률적 필수는 아니나, 어려운 케이스에서 도움."),
("재치료 비용은 보험되나요?","한국 보험은 1차 실패 후 재치료를 인정합니다. 의료기관 보험 담당자와 확인.")],
"refs":["AASLD-IDSA HCV Guidance: retreatment.","Bourliere M, et al. Sofosbuvir-velpatasvir-voxilaprevir for previously treated HCV (POLARIS-1, -4). <em>NEJM</em> 2017."]},

# === Cases for HCV ===
{"slug":"C형간염-DAA실패-재치료", "is_case":True, "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"마비렛 8주 후 RNA 재상승 — 보세비로 재치료", "h1":"마비렛 SVR12 실패 — 보세비 12주 재치료로 완치",
"desc":"genotype 1b 만성 C형간염 환자에서 마비렛 8주 후 SVR12 시점 RNA 재검출. 보세비 12주 재치료로 완치 사례.",
"keywords":"DAA실패, 보세비, 재치료",
"tags":[("DAA실패",),("보세비",)],
"case_intro":"55세 남성. 만성 C형간염(genotype 1b), 비간경변. 마비렛 8주 표준 치료. EOT 시점 RNA 음성. SVR12 시점 RNA 50 IU/mL로 재검출.",
"sections":[
{"heading":"평가","html":"<p>복용 순응도 인터뷰 — 환자가 일부 식사 외 복용 또는 결식 동반 복용. 다른 약·한약 사용 없음. 알코올 없음.</p>"},
{"heading":"재치료","html":"<p>보세비(SOF/VEL/VOX) 12주 처방, 식사와 함께 복용 강조. EOT RNA 음성, SVR12 확인. 완치.</p>"},
],
"teaching":["<strong>DAA 1차 실패의 가장 흔한 원인 — 복용 순응도</strong>. 식사 동반·정해진 시간 복용 환자 교육 핵심.","<strong>보세비는 1차 실패 후 표준 재치료</strong>","<strong>SVR12 확인 전 RNA 음성은 \"완치\"가 아님</strong> — 12주 후 RNA 음성이 SVR12.","<strong>재치료 시 환자에게 \"한 번 더 기회\"라는 메시지로 동기 부여\""],},

{"slug":"C형간염-혈액투석-치료", "is_case":True, "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"투석 환자의 마비렛 8주", "h1":"혈액투석 중인 C형간염 환자 — 마비렛 8주로 완치",
"desc":"말기 신부전·혈액투석 환자에서 C형간염 진단 후 마비렛 8주로 SVR 도달한 사례. 신장이식 평가 준비.",
"keywords":"투석, 마비렛, 신장이식",
"tags":[("투석",),("마비렛",),("신장이식",)],
"case_intro":"64세 남성. 당뇨병성 신증으로 혈액투석 4년째. 정기 검사에서 anti-HCV 양성 처음 발견 — HCV RNA 10⁵, genotype 1b. 신장이식 대기 예정.",
"sections":[
{"heading":"치료 결정","html":"<p>이식 전 SVR 도달이 표준 전략. 글레카프레비르/피브렌타스비르(마비렛) 8주 — 신기능 무관 안전. 의료기관 약사가 다른 처방약과 상호작용 점검(에리스로포이에틴·인 결합제 등은 안전).</p>"},
{"heading":"경과","html":"<p>8주 치료 완료. EOT RNA 음성. SVR12 확인. 이식 대기 등록 진행.</p>"},
],
"teaching":["<strong>혈액투석 환자의 C형간염 — 글레카프레비르/피브렌타스비르 1차</strong>","<strong>신장이식 전 SVR 도달이 표준</strong>","<strong>투석 중 안전성 양호</strong> — 일반 환자와 동등 SVR률","<strong>이식 후 면역억제 환경에서도 SVR 유지</strong>"],},

{"slug":"C형간염-HIV동반-동시치료", "is_case":True, "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"HIV·HCV 동반 — DAA + ART 동시 치료", "h1":"HIV·HCV 동반 환자에서 DAA + ART — 약물 상호작용 평가 후 동시 치료",
"desc":"HIV 안정 controlled 상태의 환자에서 HCV 진단 후 ART 조합 일시 조정 + DAA 12주로 SVR 도달.",
"keywords":"HIV, HCV, DAA, ART, 약물상호작용",
"tags":[("HIV",),("HCV",),("ART",)],
"case_intro":"45세 남성. HIV 진단 8년, ART(emtricitabine + tenofovir alafenamide + darunavir/cobicistat)로 RNA 검출 한계 이하 유지. 정기 검사에서 anti-HCV 양성·HCV RNA 양성(genotype 1a) 새로 발견.",
"sections":[
{"heading":"평가","html":"<p>감염내과·간내과 협진. 글레카프레비르/피브렌타스비르 또는 소포스부비르/벨파타스비르 중 ART와의 상호작용 평가. Darunavir/cobicistat은 글레카프레비르와 상호작용 가능 — 의료기관 약사 평가.</p>"},
{"heading":"결정과 경과","html":"<p>ART 임시 전환(darunavir/cobicistat → dolutegravir + emtricitabine/tenofovir alafenamide) 후 글레카프레비르/피브렌타스비르 8주. EOT RNA 음성, SVR12 확인. ART 원래 조합으로 복귀.</p>"},
],
"teaching":["<strong>HIV·HCV 동반은 한국에서 늘고 있는 그룹</strong>","<strong>ART 일부와 DAA 상호작용 — 약사 평가 필수</strong>","<strong>단기 ART 전환으로 DAA 완치 가능</strong>","<strong>SVR률은 HIV 단독 음성과 동등</strong>"],},

{"slug":"C형간염-임신중-발견", "is_case":True, "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"임신 8주 산전 검사에서 HCV 양성", "h1":"임신 초기 산전 검사에서 발견된 HCV — 출산 후 DAA 치료",
"desc":"임신 8주에 산전 검사에서 anti-HCV 양성 발견. 임신 중 추적 + 출산 후 DAA 8주로 완치, 영아 18개월 검사 음성.",
"keywords":"임신, HCV, 산전검사, 수직감염",
"tags":[("임신",),("산전검사",),("수직감염",)],
"case_intro":"29세 여성, 임신 8주. 산전 검사에서 anti-HCV 양성. 추가 검사 — HCV RNA 5만 IU/mL, genotype 1b. ALT 정상. 과거 정맥주사 약물 사용 이력 5년 전 종료.",
"sections":[
{"heading":"임신 중 관리","html":"<p>산과·간내과 협진. 임신 중 DAA는 표준 권고 아니라 출산 후 치료로 결정. 3개월마다 ALT·간 기능 추적. 분만 — 일반 산과 적응증으로 자연 분만, 제왕절개는 수직감염 줄이지 않음.</p>"},
{"heading":"출산 후 — DAA + 영아 추적","html":"<p>출산 4주 후 마비렛 8주 시작. SVR12 확인. 모유 수유 지속 (안전). 영아 — 6개월 후 HCV RNA 음성, 18개월 anti-HCV 음성. 수직감염 없음 확인.</p>"},
],
"teaching":["<strong>산전 검사 anti-HCV는 한국에서 점차 표준화</strong>","<strong>임신 중 DAA는 일반 권고 아님</strong>. 안전성 자료 누적 중.","<strong>제왕절개가 수직감염 줄이지 않음</strong>","<strong>모유 수유 안전</strong>","<strong>영아 검사 — 6개월 RNA 또는 18개월 anti-HCV</strong>"],},

{"slug":"C형간염-재감염", "is_case":True, "hub_path":HCV_HUB, "hub_label":HCV_LBL, "section":HCV_SEC,
"title":"DAA 완치 2년 후 재감염", "h1":"DAA SVR 후 2년 — ALT 새 상승과 재감염 발견",
"desc":"DAA 완치 후 2년 시점에 ALT 새 상승. 위험 행동 지속 환자에서 재감염 확인 후 빠른 재치료 사례.",
"keywords":"재감염, 위험행동, DAA",
"tags":[("재감염",),("위험행동",)],
"case_intro":"38세 남성. 정맥주사 약물 사용자. 2년 전 마비렛 8주로 SVR 도달. 약물 사용 계속 중이라 1년마다 RNA 추적. 이번 외래에서 ALT 95(이전 정상)와 HCV RNA 8만 IU/mL.",
"sections":[
{"heading":"평가","html":"<p>새로운 감염 — 다른 genotype 가능성 평가. Genotype 3 검출(이전 genotype 1b와 다름). 재감염 확진.</p>"},
{"heading":"재치료","html":"<p>마비렛 8주 재처방. SVR12 도달. 동시에 약물 의존성 전문 진료 의뢰, 주삿바늘 교환 프로그램 참여 권유.</p>"},
],
"teaching":["<strong>위험 행동 지속 환자 — 1년마다 RNA 추적</strong>","<strong>재감염도 DAA로 완치 가능</strong>","<strong>같은 약 다시 사용 가능</strong> — 다른 genotype이라도 pangenotype DAA로 커버","<strong>재감염은 약 실패가 아님</strong> — 환자에게 명확히 설명","<strong>약물 의존성 전문 연계 필수</strong> — 반복 재감염 예방"],},
]

if __name__ == "__main__":
    write_pages(HBV + HCV)
