"""Series 01 (간암) — 6 remaining drafts."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_articles import render_article, svg_table, svg_checklist, svg_compare_two

ARTICLES = []

# 01-1: 첫 외래
ARTICLES.append({
    "slug": "간암-진단-첫외래",
    "h1": "간암 진단을 받았을 때, 첫 외래에서 결정되는 것",
    "description": "간세포암 진단 직후 첫 외래에서 결정되는 5가지 — 병기 평가, 추가 영상, 치료팀 구성, 1차 치료 방향, 추적 일정을 정리합니다.",
    "series_slug": "간암", "series_display": "간암", "last_crumb": "진단 첫 외래",
    "section_label": "간암", "about": "간세포암",
    "tldr": "간암 진단 직후 첫 외래에서는 5가지가 결정됩니다 — <em>병기 평가, 추가 영상, 다학제 회의, 1차 치료 방향, 추적 일정</em>. 첫 만남은 검사실 결과 한 줄을 듣는 자리가 아니라, 그 다음 4–6주의 지도를 그리는 자리입니다.",
    "sections": [
        ("진단이 어떻게 확정되었는지 다시 확인",
         "<p>간암(간세포암, HCC)은 영상만으로 진단이 가능한 드문 종양입니다. KLCA-NCC 가이드라인 기준으로 <strong>역동적 CT 또는 MRI에서 동맥기 조영 증강 + 정맥기/지연기 washout 패턴</strong>이 보이면 생검 없이 진단됩니다. 첫 외래에서 본인 검사가 이 기준을 정확히 충족했는지 확인하는 것이 시작입니다.</p><p>모호한 경우 조영 초음파(CEUS), Gd-EOB-MRI, 또는 생검을 추가합니다.</p>"),
        ("병기 평가 — 무엇이 어디까지 퍼졌나",
         "<p>치료 결정의 토대입니다. 다음을 종합합니다.</p><ul><li>종양 — 크기, 개수, 위치, 혈관 침범 여부</li><li>간 기능 — Child-Pugh, ALBI, 빌리루빈, 알부민, PT</li><li>전신 상태 — ECOG performance status</li><li>원격 전이 — 흉부 CT, 뼈 스캔(증상 시)</li></ul><p>이 정보로 BCLC 단계가 정해지고, 단계별 표준치료가 결정됩니다.</p>"),
        ("다학제 진료 — 누가 함께 결정하나",
         "<p>간암은 한 진료과의 단독 결정이 아닙니다. 표준은 <strong>다학제 회의</strong>입니다.</p><ul><li>소화기내과 — 간 기능 평가, 약물 치료</li><li>외과 — 절제·이식 가능성</li><li>중재영상의학과 — 색전술·고주파소작</li><li>방사선종양학과 — SBRT·양성자</li><li>종양내과 — 면역치료·표적치료</li></ul><p>첫 외래에서 \"다음 주에 회의에서 검토하고 다시 만나뵙겠습니다\"라는 말을 들으면 그것이 표준 흐름입니다.</p>"),
        ("1차 치료 방향 — 후보 옵션은 무엇인가",
         "<p>BCLC 단계와 다학제 결과에 따라 1차 옵션이 좁혀집니다.</p><ul><li>BCLC 0–A → 절제, 고주파소작, 또는 간이식</li><li>BCLC B → 경동맥화학색전술(TACE), 한국에서는 일부 절제·SBRT 검토</li><li>BCLC C → 면역치료 (아테졸리주맙+베바시주맙, 듀발루맙+트레멜리무맙)</li><li>BCLC D → 완화 의료, 일부 이식 평가</li></ul><p>여러 옵션이 가능한 경우 환자 선호와 동반 질환을 함께 봅니다. 첫 외래에서 결정이 미뤄지는 것은 정상이며, 신중한 판단이라는 신호입니다.</p>"),
        ("추적 일정과 다음 외래까지 할 일",
         "<p>첫 외래에서 다음 단계 일정이 정해집니다.</p><ul><li>다학제 결정 통보 외래 (보통 1–2주 후)</li><li>치료 시작 일정</li><li>치료 전 보충 검사(심초음파, 폐기능 등)</li><li>B형/C형 간염 항바이러스제 시작/조정</li></ul><p>환자 입장에서 이 시기에 할 수 있는 것은 <em>금주, 충분한 영양, 약 정리(특히 한약·영양제 점검), 기록 정리</em>입니다. 갑자기 식이를 바꾸거나 새 영양제를 시작할 시점은 아닙니다.</p>"),
    ],
    "faq": [
        ("간암이라는데 증상이 전혀 없어요. 정말 맞나요?", "<p>간암은 초기에 무증상인 경우가 대부분입니다. 영상에서 진단 기준을 충족하면 증상 유무와 관계없이 치료를 시작합니다. 증상이 있을 때는 이미 진행된 단계인 경우가 많습니다.</p>"),
        ("바로 수술해야 하나요? 다학제 회의를 기다려도 되나요?", "<p>응급 상황이 아니라면 다학제 회의를 거치는 것이 표준입니다. 1–2주의 회의 대기는 예후에 영향을 주지 않으며, 오히려 더 적절한 옵션을 선택할 가능성이 높아집니다.</p>"),
        ("다른 병원에서 second opinion을 받아도 되나요?", "<p>가능하고 권장됩니다. 영상 CD와 검사 결과를 챙겨가시면 됩니다. 다만 검사 중복은 시간·비용 손실이 크므로 우선 기존 검사를 활용합니다.</p>"),
        ("B형간염 약은 계속 먹나요?", "<p>네. 모든 단계에서 항바이러스제 치료는 유지·강화됩니다. 간암 치료의 일부입니다.</p>"),
        ("간암 진단 후 회복 가능한가요?", "<p>BCLC 단계에 따라 다릅니다. 0–A 단계의 5년 생존율은 70% 이상, B는 약 40–50%, C는 면역치료 도입 후 의미 있게 향상되었습니다. 단계와 치료 옵션이 결정되면 더 구체적으로 답할 수 있습니다.</p>"),
    ],
    "refs": [
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1–120.", "10.17998/jlc.2022.11.07", None),
        ("Singal AG, Llovet JM, Yarchoan M, et al. AASLD Practice Guidance on prevention, diagnosis, and treatment of hepatocellular carcinoma. <em>Hepatology</em>. 2023;78(6):1922–1965.", "10.1097/HEP.0000000000000466", "37199193"),
        ("European Association for the Study of the Liver. EASL Clinical Practice Guidelines: Management of hepatocellular carcinoma. <em>J Hepatol</em>. 2018;69(1):182–236.", "10.1016/j.jhep.2018.03.019", None),
        ("Reig M, Forner A, Rimola J, et al. BCLC strategy for prognosis prediction and treatment recommendation: The 2022 update. <em>J Hepatol</em>. 2022;76(3):681–693.", "10.1016/j.jhep.2021.11.018", "34801630"),
    ],
    "svgs": [
        svg_checklist("첫 외래 결정 5가지",
                      ["1. 진단 확정 — 영상 기준 재검토",
                       "2. 병기 평가 — 종양·간기능·전신 상태",
                       "3. 다학제 회의 일정 — 보통 1–2주 후",
                       "4. 1차 치료 옵션 좁히기",
                       "5. 추적·치료 시작 일정 확정"],
                      caption="첫 외래는 \"진단 한 줄\"이 아니라 다음 4–6주의 지도"),
        svg_table("BCLC 단계별 1차 옵션 (KLCA-NCC 적용 일부 차이)",
                  ["단계", "표준 1차 옵션"],
                  [["0 / A 초기", "절제 · 이식 · 고주파소작"],
                   ["B 중간기", "경동맥화학색전술(TACE), 일부 절제·SBRT"],
                   ["C 진행기", "면역치료 1차 (atezo+bev, durva+treme)"],
                   ["D 말기", "완화 의료, 일부 이식 평가"]],
                  caption="첫 외래에서 좁혀지는 옵션 — 다학제에서 환자별로 미세 조정"),
    ],
    "related": [
        ("/간암-BCLC병기/", "BCLC 병기와 치료 옵션 — 무엇이 어떤 환자에게"),
        ("/간암-치료-선택/", "절제술 vs 색전술 vs 방사선 — 선택의 기준"),
        ("/B형간염-간암검진/", "B형간염 환자가 6개월마다 간암 검진을 받아야 하는 이유"),
    ],
})

# 01-3: 절제 vs 색전 vs 방사선
ARTICLES.append({
    "slug": "간암-치료-선택",
    "h1": "절제술 vs 색전술 vs 방사선 — 선택의 기준",
    "description": "간세포암 1차 국소 치료 옵션 — 외과 절제, 경동맥화학색전술(TACE), 방사선치료(SBRT/양성자)의 적응증·이득·한계를 비교합니다.",
    "series_slug": "간암", "series_display": "간암", "last_crumb": "치료 선택",
    "section_label": "간암", "about": "간세포암",
    "tldr": "초기·중간기 간세포암의 국소 치료는 절제·색전·방사선 세 축이 있고, <em>종양 위치·크기·간 기능·혈관 침범</em>이 결정 요소입니다. 절제는 단일·잘 분리된 종양에 강하고, TACE는 다발성에 표준, SBRT/양성자는 절제 곤란·고위험 위치에서 점차 대안. 한 가지가 절대 우월하지 않으며 다학제로 결정합니다.",
    "sections": [
        ("외과 절제 — 가장 치료적인 옵션",
         "<p>간 기능이 보존된 단일·잘 분리된 종양에서 1차 옵션입니다.</p><ul><li>적응증: Child-Pugh A, 정상 빌리루빈, HVPG &lt; 10 mmHg, 종양 절제 후 간 잔여 충분</li><li>5년 생존: 약 50–70% (단일·소형에서 더 높음)</li><li>한계: 다발성·혈관 침범·간 기능 불량에서 위험 큼. 한국은 양엽성·다발성에서도 부분 절제 시도</li></ul><p>로보트·복강경 절제가 점차 보편화되어 회복이 빨라졌습니다.</p>"),
        ("경동맥화학색전술 (TACE) — 중간기 표준",
         "<p>다발성 종양 또는 절제 곤란 위치에 1차 표준입니다.</p><ul><li>방법: 대퇴동맥으로 카테터 진입 → 종양 공급 동맥에 항암제+색전 물질 주입</li><li>적응증: BCLC B, Child-Pugh A–B, 혈관 침범 없음</li><li>이득: 종양 위축, 다회 반복 가능</li><li>한계: 완전 괴사 어려움, 반복 시 간 기능 부담</li></ul><p>최근에는 약물 용출 비드(DEB-TACE), 방사선색전술(TARE/Y-90)이 상황에 따라 대안이 됩니다.</p>"),
        ("방사선치료 — SBRT와 양성자",
         "<p>최근 5–10년 사이 입지가 크게 넓어진 옵션입니다.</p><ul><li>SBRT (체부 정위 방사선) — 3–5회 고선량 분할. 절제 곤란한 위치, 작은 종양에서 절제와 비교 가능한 국소 제어</li><li>양성자 — 한국에서 시행. 정상 간 보존에 유리, 큰 종양·중심 위치에서 유용</li><li>적응증: 절제·소작 곤란, 일부 혈관 침범 환자</li><li>한계: 큰 종양에서는 단독 치료보다 다른 옵션과 병용</li></ul><p>한국 KLCA-NCC 가이드라인은 BCLC C 일부에서도 방사선치료를 옵션으로 인정합니다.</p>"),
        ("선택의 결정 인자",
         "<p>한 환자에서 어느 옵션이 적합한가는 다음으로 결정됩니다.</p><ul><li>종양 — 단일/다발, 크기, 위치(중심부 vs 표면), 혈관 침범</li><li>간 기능 — Child-Pugh, ALBI, 빌리루빈, HVPG</li><li>잔여 간 부피 (절제 후 간부전 예측)</li><li>환자 — 나이, 동반 질환, 출혈 위험, 환자 선호</li><li>병원 인프라 — 전문 인력·장비 가용성</li></ul><p>두 옵션이 비슷할 때 환자 선호가 결정 무게를 가집니다.</p>"),
        ("결합 치료와 신경향",
         "<p>최근에는 단일 치료보다 결합이 늘고 있습니다.</p><ul><li>TACE + SBRT — 큰 종양·문맥 침범 일부에서</li><li>TACE → 면역치료 — 진행 시 전환</li><li>다운스테이징 → 절제·이식 — 큰 종양을 줄여 근치 치료 후보로</li></ul><p>면역치료(atezo+bev)와 국소 치료의 결합은 임상시험이 활발히 진행 중이며 향후 1차 옵션 지형이 바뀔 가능성이 큽니다.</p>"),
    ],
    "faq": [
        ("절제와 고주파소작 중 어느 게 좋나요?", "<p>3 cm 이하 단일 종양에서는 두 옵션의 5년 생존이 비슷합니다. 위치·간 기능·환자 선호로 결정합니다.</p>"),
        ("TACE는 몇 번까지 받나요?", "<p>정해진 횟수는 없습니다. 효과·간 기능을 보면서 반복합니다. 간 기능이 떨어지거나 효과가 줄면 다른 옵션으로 전환합니다.</p>"),
        ("SBRT는 한 번에 끝나나요?", "<p>3–5회 분할이 표준입니다. 1–2주에 걸쳐 외래 통원으로 가능합니다.</p>"),
        ("양성자치료는 보험되나요?", "<p>일부 적응증에서 보험 적용됩니다. 모든 간암에서 자동 적용은 아니므로 진료 시 확인이 필요합니다.</p>"),
        ("치료 후 종양이 다시 생기면 같은 치료를 또 받나요?", "<p>가능합니다. 다만 첫 치료 효과·간 기능 변화·새 종양의 위치를 다학제에서 다시 평가합니다.</p>"),
    ],
    "refs": [
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1–120.", "10.17998/jlc.2022.11.07", None),
        ("Llovet JM, Real MI, Montaña X, et al. Arterial embolisation or chemoembolisation versus symptomatic treatment in patients with unresectable hepatocellular carcinoma: a randomised controlled trial. <em>Lancet</em>. 2002;359(9319):1734–1739.", "10.1016/S0140-6736(02)08649-X", "12049862"),
        ("Bujold A, Massey CA, Kim JJ, et al. Sequential phase I and II trials of stereotactic body radiotherapy for locally advanced hepatocellular carcinoma. <em>J Clin Oncol</em>. 2013;31(13):1631–1639.", "10.1200/JCO.2012.44.1659", "23547075"),
        ("European Association for the Study of the Liver. EASL Clinical Practice Guidelines: Management of hepatocellular carcinoma. <em>J Hepatol</em>. 2018;69(1):182–236.", "10.1016/j.jhep.2018.03.019", None),
        ("Park JW, Kim YJ, Kim DY, et al. Sorafenib with or without concurrent transarterial chemoembolization in patients with advanced hepatocellular carcinoma: The phase III STAH trial. <em>J Hepatol</em>. 2019;70(4):684–691.", "10.1016/j.jhep.2018.11.029", "30529386"),
    ],
    "svgs": [
        svg_table("세 옵션 비교",
                  ["", "절제", "TACE", "SBRT/양성자"],
                  [["BCLC", "0–A, 일부 B", "B, 일부 A", "A·B·일부 C"],
                   ["반복", "일반적으로 1회", "여러 회 가능", "재조사 신중"],
                   ["간 기능 부담", "큼 (수술)", "중등도", "낮음 (간외 영향 적음)"],
                   ["회복", "수일–수주", "1–3일", "외래 통원"]],
                  caption="단일 우열은 없음 — 종양·간기능·환자에 따라 결정"),
        svg_checklist("선택을 결정하는 5가지 인자",
                      ["종양 — 단일/다발, 크기, 위치, 혈관 침범",
                       "간 기능 — Child-Pugh, ALBI, HVPG",
                       "잔여 간 부피 (절제 후 간부전 예측)",
                       "환자 동반 질환·출혈 위험·선호",
                       "병원 인프라 — 전문 인력·장비 가용성"],
                      caption="다학제 회의에서 종합 평가"),
    ],
    "related": [
        ("/간암-BCLC병기/", "BCLC 병기와 치료 옵션 — 무엇이 어떤 환자에게"),
        ("/간암-진단-첫외래/", "간암 진단을 받았을 때, 첫 외래에서 결정되는 것"),
        ("/간암-면역치료-1차/", "면역치료 1차 시대 — atezo+bev과 그 이후"),
    ],
})

# 01-4: 면역치료 1차
ARTICLES.append({
    "slug": "간암-면역치료-1차",
    "h1": "면역치료 1차 시대 — atezolizumab+bevacizumab과 그 이후",
    "description": "진행성 간세포암(BCLC C)의 1차 표준치료로 자리 잡은 면역치료 — IMbrave150 이후의 옵션, 부작용, 한국 임상 적용을 정리합니다.",
    "series_slug": "간암", "series_display": "간암", "last_crumb": "면역치료 1차",
    "section_label": "간암", "about": "간세포암",
    "tldr": "진행성 간암 BCLC C 1차 치료가 2020년 IMbrave150 이후 <em>아테졸리주맙+베바시주맙(atezo+bev)</em>으로 바뀌었습니다. 2022년 HIMALAYA로 <em>듀발루맙+트레멜리무맙(STRIDE)</em>이 두 번째 1차 옵션이 되었습니다. 두 옵션 모두 sorafenib 단독보다 생존을 의미 있게 연장했고, 한국 보험에서도 일부 환자에서 사용 가능합니다.",
    "sections": [
        ("왜 면역치료로 흐름이 바뀌었나",
         "<p>2007–2019년의 1차 표준은 sorafenib(경구 표적치료)였습니다. 중앙 생존 기간 약 10–12개월. 면역체크포인트 억제제(PD-L1, CTLA-4 차단)가 다른 암에서 효과를 보이며 간암에도 시도되었고, 2020년 IMbrave150에서 처음으로 sorafenib보다 우월함이 입증되었습니다.</p><ul><li>아테졸리주맙(PD-L1) + 베바시주맙(VEGF) 병합</li><li>중앙 생존 19.2개월 vs sorafenib 13.4개월</li><li>객관적 반응률 30% vs 11%</li></ul><p>이 결과로 진행성 간암의 1차가 거의 8년 만에 바뀌었습니다.</p>"),
        ("두 번째 1차 옵션 — HIMALAYA / STRIDE 요법",
         "<p>2022년 HIMALAYA에서 <strong>듀발루맙(PD-L1) + 트레멜리무맙(CTLA-4) 1회</strong> (\"STRIDE\" 요법)이 sorafenib보다 우월함이 입증되었습니다.</p><ul><li>중앙 생존 16.4개월 vs sorafenib 13.8개월</li><li>출혈 위험이 있는 환자(과거 정맥류 출혈 등)에서 베바시주맙을 못 쓰는 경우의 대안</li><li>4년 생존이 약 25%로 보고 — 면역치료의 \"꼬리\" 효과</li></ul><p>두 옵션 사이의 직접 비교 시험은 없으며, 환자 동반 질환과 출혈 위험으로 결정합니다.</p>"),
        ("부작용과 모니터링",
         "<p>면역치료 부작용은 sorafenib과 다른 양상입니다.</p><ul><li>면역 매개 — 갑상선 기능 이상, 폐렴, 대장염, 간염, 부신 기능 저하 등 <em>어떤 장기에든</em> 가능</li><li>베바시주맙 추가 — 출혈(특히 정맥류), 단백뇨, 고혈압, 혈전</li><li>드물지만 중증 부작용 조기 인지가 핵심</li></ul><p>치료 시작 전 정맥류 평가(내시경)가 필수이며, 출혈 위험이 높으면 STRIDE 또는 다른 옵션으로 전환합니다.</p>"),
        ("한국 임상 적용과 보험",
         "<p>한국은 두 옵션 모두 도입되어 있으며 일부 적응증에서 보험 적용됩니다.</p><ul><li>아테졸리주맙+베바시주맙 — Child-Pugh A, BCLC B-C, 일부 정맥류 출혈 이력 제외 등 조건부 보험</li><li>듀발루맙+트레멜리무맙 — 보험 진행 중, 일부 적응증</li><li>비보험 시 약가 부담이 큼 — 진료의·환자가 함께 결정</li></ul><p>매년 가이드라인·보험 기준이 갱신되므로 최신 상태는 진료 시 확인이 필요합니다.</p>"),
        ("진행 시 다음 단계와 결합 치료의 미래",
         "<p>면역치료 1차에 진행하면 2차로 다음을 고려합니다.</p><ul><li>경구 표적 — 소라페닙, 렌바티닙, 카보잔티닙</li><li>다른 면역치료 — pembrolizumab, ramucirumab</li><li>임상시험 — 새 조합·표적</li></ul><p>현재 활발한 임상시험: 면역치료 + 국소치료(TACE/SBRT) 결합, 1차 후 maintenance, 더 일찍 이식·절제와 결합하는 시도. 향후 5년 안에 1차 지형이 또 바뀔 가능성이 큽니다.</p>"),
    ],
    "faq": [
        ("간 기능이 떨어졌는데도 면역치료를 받을 수 있나요?", "<p>대부분의 임상시험은 Child-Pugh A를 대상으로 했습니다. Child-Pugh B에서의 안전성·효과는 제한적이고, C에서는 일반적으로 권장되지 않습니다.</p>"),
        ("면역치료에 반응이 좋으면 완치되나요?", "<p>완치라는 표현보다 \"장기간 반응 유지\"가 정확합니다. 일부 환자에서 종양이 줄어 절제·이식 후보로 전환(다운스테이징)되기도 합니다.</p>"),
        ("부작용이 무서운데, 외래 추적은 어떻게 하나요?", "<p>3–4주마다 혈액검사(간기능·갑상선·신기능·요단백·혈당)를 봅니다. 새 증상(설사, 호흡곤란, 피부 발진, 극심한 피로)이 있으면 다음 외래 기다리지 말고 알려야 합니다.</p>"),
        ("정맥류가 있어요. 베바시주맙을 못 쓰나요?", "<p>출혈 위험이 높으면 일반적으로 회피합니다. 듀발루맙+트레멜리무맙(STRIDE)이 대안이 될 수 있습니다.</p>"),
        ("치료 비용이 많이 든다는데 부담이 어떻게 되나요?", "<p>적응증에 맞으면 산정특례·보험으로 본인부담이 줄어듭니다. 정확한 비용은 병원 행정과 함께 확인이 필요합니다.</p>"),
    ],
    "refs": [
        ("Finn RS, Qin S, Ikeda M, et al. Atezolizumab plus Bevacizumab in Unresectable Hepatocellular Carcinoma (IMbrave150). <em>N Engl J Med</em>. 2020;382(20):1894–1905.", "10.1056/NEJMoa1915745", "32402160"),
        ("Abou-Alfa GK, Lau G, Kudo M, et al. Tremelimumab plus Durvalumab in Unresectable Hepatocellular Carcinoma (HIMALAYA). <em>NEJM Evid</em>. 2022;1(8):EVIDoa2100070.", "10.1056/EVIDoa2100070", None),
        ("Singal AG, Llovet JM, Yarchoan M, et al. AASLD Practice Guidance on prevention, diagnosis, and treatment of hepatocellular carcinoma. <em>Hepatology</em>. 2023;78(6):1922–1965.", "10.1097/HEP.0000000000000466", "37199193"),
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1–120.", "10.17998/jlc.2022.11.07", None),
        ("Cheng AL, Qin S, Ikeda M, et al. Updated efficacy and safety data from IMbrave150: Atezolizumab plus bevacizumab vs. sorafenib for unresectable hepatocellular carcinoma. <em>J Hepatol</em>. 2022;76(4):862–873.", "10.1016/j.jhep.2021.11.030", "34902530"),
    ],
    "svgs": [
        svg_table("진행성 간암 1차 옵션 (2026 기준)",
                  ["요법", "조합", "주요 시험", "특징"],
                  [["Atezo + Bev", "PD-L1 + VEGF", "IMbrave150", "1차 표준, 출혈 위험 평가 필수"],
                   ["STRIDE", "Durva + Treme×1", "HIMALAYA", "출혈 위험 환자의 대안"],
                   ["Sorafenib", "TKI 단독", "SHARP", "면역치료 부적합 시"],
                   ["Lenvatinib", "TKI 단독", "REFLECT", "Sorafenib 대안 (TKI)"]],
                  caption="진행성 BCLC C 환자의 옵션 — 환자별 동반 질환과 출혈 위험으로 결정"),
        svg_checklist("면역치료 외래 모니터링 항목",
                      ["3–4주마다 혈액검사 — 간·갑상선·신기능·요단백·혈당",
                       "내시경 — 베바시주맙 시작 전 정맥류 평가",
                       "심혈관 — 혈압·심부전 증상",
                       "새 증상 즉시 보고 — 설사·호흡곤란·발진·극심한 피로",
                       "정기 영상 — 보통 8–12주 간격으로 반응 평가"],
                      caption="면역 매개 부작용은 어느 장기에든 가능 — 조기 인지가 결정적"),
    ],
    "related": [
        ("/간암-BCLC병기/", "BCLC 병기와 치료 옵션 — 무엇이 어떤 환자에게"),
        ("/간암-치료-선택/", "절제술 vs 색전술 vs 방사선 — 선택의 기준"),
        ("/updates/MAESTRO-NASH-resmetirom-NEJM-2024/", "최신 지견 — 주요 hepatology 논문 노트"),
    ],
})

# 01-5: 간이식 (HCC 관점)
ARTICLES.append({
    "slug": "간암-간이식",
    "h1": "간암에서의 간이식 — 적응증과 한국의 흐름",
    "description": "간세포암 환자에서 간이식의 적응증(Milan, UCSF 기준), 한국 KLCA-NCC 적응증, 다운스테이징, 살아있는 기증자 이식까지를 정리합니다.",
    "series_slug": "간암", "series_display": "간암", "last_crumb": "간이식",
    "section_label": "간암", "about": "간이식",
    "tldr": "간세포암 환자에서 이식은 종양과 간경변을 한 번에 해결하는 옵션입니다. <em>Milan criteria</em>(단일 ≤5 cm 또는 ≤3개·각 ≤3 cm)가 표준이고, 한국은 더 넓은 KLCA-NCC 기준도 사용합니다. 큰 종양은 <em>다운스테이징</em>으로 기준에 들어오면 이식 후보가 됩니다. 한국은 살아있는 기증자(LDLT) 비율이 세계 최고 수준입니다.",
    "sections": [
        ("간이식이 다른 치료와 다른 점",
         "<p>절제·색전·방사선·면역치료는 종양만 다룹니다. 간이식은 <strong>종양과 간경변을 동시에 해결</strong>합니다. 따라서 다음 환자에서 강력한 옵션입니다.</p><ul><li>간 기능이 나쁘고 종양이 작은 경우 — 절제 곤란</li><li>다발성 종양이지만 일정 범위 내</li><li>반복 재발하는 환자</li></ul><p>5년 생존율 70–80%로 매우 좋으나, 평생 면역억제제 복용·기증자 가용성이 한계입니다.</p>"),
        ("Milan과 UCSF 기준",
         "<p>1996년 Mazzaferro의 <strong>Milan criteria</strong>:</p><ul><li>단일 ≤ 5 cm <em>또는</em> 최대 3개·각 ≤ 3 cm</li><li>혈관 침범 없음, 원격 전이 없음</li></ul><p>이 기준 내 환자의 이식 후 5년 생존이 약 75%로, 일반 간이식 환자와 비슷합니다.</p><p><strong>UCSF criteria</strong> (좀 더 넓음):</p><ul><li>단일 ≤ 6.5 cm 또는 최대 3개·최대 ≤ 4.5 cm·총 ≤ 8 cm</li><li>예후가 Milan과 유사함이 검증되어 일부 센터에서 사용</li></ul>"),
        ("한국 KLCA-NCC 기준",
         "<p>한국은 종양 부담을 더 넓게 보는 <strong>modified UCSF</strong> 또는 자체 기준을 사용합니다.</p><ul><li>종양 크기·개수의 절대 한계 외에 종양표지자(AFP, PIVKA-II)와 동적 영상 패턴을 함께 고려</li><li>AFP &gt; 1000 ng/mL 같은 고위험 환자는 기준 내라도 신중 평가</li><li>한국의 LDLT 비율이 높아 기증자 가용성이 결정 무게에 영향</li></ul>"),
        ("다운스테이징 — 큰 종양을 줄여 후보로",
         "<p>처음에는 기준 밖이지만 치료에 잘 반응하여 줄어들면 이식 후보가 되는 흐름입니다.</p><ul><li>방법: TACE, SBRT, 면역치료 단독 또는 결합</li><li>목표: Milan 또는 UCSF 기준 내로 진입</li><li>관찰 기간: 보통 3–6개월 안정 후 등록</li><li>예후: 다운스테이징 성공한 환자의 이식 후 5년 생존이 직접 기준 내 환자와 유사함이 보고</li></ul>"),
        ("살아있는 기증자 이식 (LDLT) — 한국의 강점",
         "<p>한국은 LDLT가 전체 간이식의 약 70%를 차지합니다.</p><ul><li>장점 — 대기 짧음(수 주~수 개월), 일정 조정 가능, 기증자 간이 \"신선한\" 상태</li><li>기증자 — 가족 등, 엄격한 평가 (수술 사망률 약 0.2%)</li><li>HCC에서의 LDLT — 종양 진행을 기다리지 않아 이식 시점이 빠름</li></ul><p>다만 종양이 너무 크거나 빠르게 진행하는 환자에서는 LDLT 후 재발 위험이 높을 수 있어 신중 평가합니다.</p>"),
    ],
    "faq": [
        ("종양이 7 cm인데 이식 후보가 안 되나요?", "<p>Milan 기준 밖이지만 다운스테이징으로 5 cm 이하로 줄이면 후보가 됩니다. 다학제 평가가 필요합니다.</p>"),
        ("이식 받기까지 얼마나 기다리나요?", "<p>한국은 LDLT가 활발해 평균 대기 기간이 짧습니다. 뇌사자 이식은 더 깁니다.</p>"),
        ("이식 후 종양이 다시 생길 수 있나요?", "<p>가능합니다. 첫 2년이 가장 위험하며 이후에도 추적이 필요합니다. 면역억제제 종류·용량 조정으로 재발을 줄이는 시도들이 있습니다.</p>"),
        ("AFP가 높으면 이식이 어렵나요?", "<p>AFP 수치 자체로 배제하지 않지만, 매우 높으면(예: 1000 ng/mL 이상) 신중 평가합니다. 동적 변화(다운스테이징 후 감소 여부)를 함께 봅니다.</p>"),
        ("면역억제제는 평생 먹어야 하나요?", "<p>네, 평생입니다. HCC 이식 환자에서는 mTOR 억제제(시롤리무스 등)가 재발 감소에 일부 효과가 보고됩니다.</p>"),
    ],
    "refs": [
        ("Mazzaferro V, Regalia E, Doci R, et al. Liver transplantation for the treatment of small hepatocellular carcinomas in patients with cirrhosis. <em>N Engl J Med</em>. 1996;334(11):693–699.", "10.1056/NEJM199603143341104", "8594428"),
        ("Yao FY, Ferrell L, Bass NM, et al. Liver transplantation for hepatocellular carcinoma: expansion of the tumor size limits does not adversely impact survival. <em>Hepatology</em>. 2001;33(6):1394–1403.", "10.1053/jhep.2001.24563", "11391528"),
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1–120.", "10.17998/jlc.2022.11.07", None),
        ("Mazzaferro V, Citterio D, Bhoori S, et al. Liver transplantation in hepatocellular carcinoma after tumour downstaging (XXL): a randomised, controlled, phase 2b/3 trial. <em>Lancet Oncol</em>. 2020;21(7):947–956.", "10.1016/S1470-2045(20)30224-2", "32615109"),
        ("Lee SG. A complete treatment of adult living donor liver transplantation: a review of surgical technique and current updates from 1991 initial experiences. <em>Am J Transplant</em>. 2015;15(1):17–38.", "10.1111/ajt.12907", "25358749"),
    ],
    "svgs": [
        svg_table("간암 이식 기준 비교",
                  ["기준", "정의"],
                  [["Milan", "단일 ≤5 cm 또는 ≤3개·각 ≤3 cm, 혈관 침범 없음"],
                   ["UCSF", "단일 ≤6.5 cm 또는 ≤3개·총 ≤8 cm·최대 ≤4.5 cm"],
                   ["KLCA-NCC", "확장 기준 + 종양표지자(AFP, PIVKA-II)·영상 동적 패턴"]],
                  caption="기준에 들면 이식 후 5년 생존 약 70–75%"),
        svg_checklist("다운스테이징 흐름",
                      ["1. 처음 평가 — Milan/UCSF 기준 밖",
                       "2. TACE, SBRT, 면역치료로 종양 축소 시도",
                       "3. 영상 추적 — 3–6개월 안정 확인",
                       "4. 기준 내 진입 시 이식 등록",
                       "5. 이식 후 추적 — 첫 2년이 재발 최고 위험"],
                      caption="다운스테이징 성공 후 이식은 직접 기준 내 환자와 비슷한 예후"),
    ],
    "related": [
        ("/간암-BCLC병기/", "BCLC 병기와 치료 옵션 — 무엇이 어떤 환자에게"),
        ("/간경변-간이식-평가/", "간이식 평가 — 누가, 언제 시작하나"),
        ("/간암-치료-선택/", "절제술 vs 색전술 vs 방사선 — 선택의 기준"),
    ],
})

# 01-9: 재발 추적
ARTICLES.append({
    "slug": "간암-재발-추적",
    "h1": "간암 재발 추적 — 첫 5년의 일정",
    "description": "간세포암 치료 후 재발 패턴(첫 2년 vs 그 이후), 표준 추적 일정(영상·종양표지자), 재발 시 대응을 정리합니다.",
    "series_slug": "간암", "series_display": "간암", "last_crumb": "재발 추적",
    "section_label": "간암", "about": "간세포암 재발",
    "tldr": "간암 치료 후 재발은 두 가지 패턴이 있습니다 — <em>치료한 종양 부위 재발(2년 내가 많음)</em>과 <em>새 결절 발생(2년 이후·간 다른 부위)</em>. 첫 2년은 가장 위험한 시기로 3–4개월 간격 추적이 표준입니다. 재발하면 위치·시점·간 기능에 따라 두 번째 치료가 결정되며, 일부에서 다시 근치 치료가 가능합니다.",
    "sections": [
        ("두 가지 재발 패턴",
         "<p>간암 재발은 시점에 따라 의미가 다릅니다.</p><ul><li><strong>조기 재발 (2년 이내)</strong> — 처음 치료한 종양의 미세 잔여 또는 미세전이가 자라난 것. 보통 같은 위치 또는 인접부.</li><li><strong>후기 재발 (2년 이후)</strong> — 간경변 자체에서 새 종양이 발생. 다른 위치, 새로운 결절. 사실상 \"새로운 간암\"에 가까움.</li></ul><p>두 패턴의 예후가 다르며 후기 재발이 일반적으로 더 좋은 경과를 보입니다.</p>"),
        ("표준 추적 일정",
         "<p>치료 후 표준 추적 (KLCA-NCC, AASLD 기반):</p><ul><li>치료 직후 1개월 — 첫 효과 평가 영상</li><li>1–2년 — <strong>3–4개월마다</strong> 동적 CT/MRI + AFP·PIVKA-II</li><li>3–5년 — <strong>6개월마다</strong> 같은 검사</li><li>5년 이후 — 6개월–1년 간격, 평생 추적</li></ul><p>간경변 환자는 \"치료 완료\"라는 시점이 없습니다. 새 결절 발생 위험이 평생 있어 추적이 멈추지 않습니다.</p>"),
        ("영상과 종양표지자의 역할",
         "<p>두 가지를 함께 봅니다.</p><ul><li><strong>영상</strong> — 동적 CT 또는 MRI(Gd-EOB가 작은 결절에 우월). 한국은 특히 EOB-MRI가 활발히 사용됨</li><li><strong>AFP</strong> — 진단 시 높았던 환자에서 추적 마커로 유용. 정상이었던 환자에서 감시 가치는 제한</li><li><strong>PIVKA-II (DCP)</strong> — AFP와 보완. 한국에서 표준</li></ul><p>두 표지자 모두 정상이라도 영상에서 재발이 발견될 수 있어, 영상이 가장 우선합니다.</p>"),
        ("재발 위험 인자",
         "<p>다음이 있으면 재발 위험이 높아 더 적극적 추적이 필요합니다.</p><ul><li>처음 종양 — 큰 크기, 다발성, 미세혈관 침범, 위성 결절</li><li>높은 종양표지자 — AFP &gt; 1000, PIVKA-II 매우 높음</li><li>기저 간 — 간경변, 활동성 B형/C형 간염, 음주 지속</li><li>치료 후 잔여 — 영상에서 \"의심성 변화\"</li></ul><p>이런 인자가 있으면 표준 일정보다 짧은 간격으로 추적합니다.</p>"),
        ("재발했을 때의 대응",
         "<p>두 번째 치료 결정은 첫 치료와 같은 흐름입니다.</p><ul><li>다학제에서 재평가 — 종양·간 기능·치료 이력</li><li>국소 재발 — 절제·소작·SBRT·TACE 가능. 일부에서 다시 근치 치료</li><li>다발성·진행 — 면역치료 또는 임상시험</li><li>이식 후보 — 일부 재발 환자도 다운스테이징 후 이식 가능</li></ul><p>재발이 나쁜 소식이지만 \"끝\"은 아닙니다. 이전 치료 효과·간 기능·환자 상태로 새 옵션이 결정됩니다.</p>"),
    ],
    "faq": [
        ("재발 안 하면 \"완치\"라고 부를 수 있나요?", "<p>5년 무재발이면 임상적으로 좋은 신호이지만, 간경변이 있는 한 새 결절 위험이 남아 \"완치\"라는 표현은 신중합니다. 평생 추적이 표준입니다.</p>"),
        ("AFP가 정상인데도 재발할 수 있나요?", "<p>가능합니다. 약 30–40%의 간암은 AFP 정상이며, 이런 환자는 영상이 더 결정적입니다.</p>"),
        ("CT를 이렇게 자주 받으면 방사선이 걱정돼요.", "<p>적절한 검사로 방사선 노출을 평가하지만, 간암 추적의 이득이 위험을 크게 상회합니다. 일부에서는 EOB-MRI로 일부 CT를 대체합니다.</p>"),
        ("재발한 종양을 절제할 수 있나요?", "<p>가능합니다. 위치·간 기능·이전 치료 이력에 따라 결정합니다. 다학제에서 재평가합니다.</p>"),
        ("재발 후 면역치료를 받으면 부작용이 더 심한가요?", "<p>이전 치료와 무관하게 면역치료의 부작용 양상은 비슷합니다. 다만 누적된 간 기능 저하가 있으면 더 신중한 모니터링이 필요합니다.</p>"),
    ],
    "refs": [
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1–120.", "10.17998/jlc.2022.11.07", None),
        ("Singal AG, Llovet JM, Yarchoan M, et al. AASLD Practice Guidance on prevention, diagnosis, and treatment of hepatocellular carcinoma. <em>Hepatology</em>. 2023;78(6):1922–1965.", "10.1097/HEP.0000000000000466", "37199193"),
        ("Imamura H, Matsuyama Y, Tanaka E, et al. Risk factors contributing to early and late phase intrahepatic recurrence of hepatocellular carcinoma after hepatectomy. <em>J Hepatol</em>. 2003;38(2):200–207.", "10.1016/s0168-8278(02)00360-4", "12547409"),
        ("Bruix J, Takayama T, Mazzaferro V, et al. Adjuvant sorafenib for hepatocellular carcinoma after resection or ablation (STORM): a phase 3, randomised, double-blind, placebo-controlled trial. <em>Lancet Oncol</em>. 2015;16(13):1344–1354.", "10.1016/S1470-2045(15)00198-9", "26361969"),
    ],
    "svgs": [
        svg_table("표준 추적 일정",
                  ["기간", "간격", "검사"],
                  [["치료 직후 1개월", "1회", "첫 효과 평가 영상"],
                   ["1–2년", "3–4개월", "동적 CT/MRI + AFP + PIVKA-II"],
                   ["3–5년", "6개월", "같은 검사"],
                   ["5년 이후", "6–12개월", "같은 검사 (평생)"]],
                  caption="간경변이 있는 한 추적은 끝나지 않음"),
        svg_checklist("재발 위험을 높이는 인자",
                      ["큰 종양·다발성·미세혈관 침범·위성 결절",
                       "높은 종양표지자 (AFP > 1000 등)",
                       "활동성 B형/C형 간염·음주 지속",
                       "간경변 진행",
                       "치료 후 영상의 \"의심성 변화\""],
                      caption="이런 인자가 있으면 표준 일정보다 짧게 추적"),
    ],
    "related": [
        ("/간암-BCLC병기/", "BCLC 병기와 치료 옵션 — 무엇이 어떤 환자에게"),
        ("/B형간염-간암검진/", "B형간염 환자가 6개월마다 간암 검진을 받아야 하는 이유"),
        ("/알파태아단백/", "AFP(알파태아단백) 수치 — 정상범위와 간암 의심 기준"),
    ],
})

# 01-10: 식이·일상
ARTICLES.append({
    "slug": "간암-식이-일상",
    "h1": "간암 환자의 식이·일상 — 과도한 제한도 위험합니다",
    "description": "간암 환자가 치료 중·후 알아둘 영양 권고, 운동, 회피할 약·영양제, 일상 관리를 정리합니다. \"무엇을 더 해야 하나\"와 \"하지 말아야 할 것\".",
    "series_slug": "간암", "series_display": "간암", "last_crumb": "식이·일상",
    "section_label": "간암", "about": "간세포암",
    "tldr": "간암 진단 후 흔한 오해 두 가지 — \"극단적 식이 제한이 도움된다\"와 \"한약·영양제로 보완된다\". 둘 다 위험할 수 있습니다. <em>충분한 단백·열량 섭취, 가벼운 운동, 검증되지 않은 보충제 회피, 약물 점검</em>이 외래에서 일관되게 권고하는 4가지입니다.",
    "sections": [
        ("\"무엇을 먹어야 하나\" — 영양의 기본",
         "<p>간암 환자는 동시에 간경변·치료 부담을 안고 있어 영양실조 위험이 높습니다.</p><ul><li>열량 — 30–35 kcal/kg(이상 체중)/일</li><li>단백 — 1.2–1.5 g/kg/일 (간성혼수 우려에도 단백 제한은 옛 권고)</li><li>식이 횟수 — 3끼 + 간식 + 취침 전 200 kcal 야식</li><li>식물성·유제품 단백 우선</li></ul><p>특정 \"슈퍼푸드\"보다 균형 잡힌 식단의 패턴이 결정적입니다.</p>"),
        ("\"무엇을 피해야 하나\" — 약·영양제·민간요법",
         "<p>다음은 외래에서 자주 만나는 위험 카테고리입니다.</p><ul><li>한약재 — 백선·하수오 등 보고 사례 다수</li><li>녹차 농축 추출물 (catechin 농축 보충제)</li><li>'간에 좋다'는 출처 불명 영양제</li><li>NSAIDs (이부프로펜 등) — 신독성·출혈</li><li>벤조다이아제핀 — 간성혼수 유발</li><li>알코올 — 한 잔도 권장하지 않음</li></ul><p>새로 시작하는 모든 제품은 외래에 알리세요.</p>"),
        ("운동 — 근육이 곧 회복력",
         "<p>간암 환자에서 근감소증이 흔하고, 그 자체로 치료 합병증·사망률을 높입니다. 그래서 운동은 단순 권장이 아니라 \"치료의 일부\"입니다.</p><ul><li>유산소 — 주 5회, 30분 가벼운 걷기</li><li>저항 운동 — 주 2–3회, 큰 근육군 위주</li><li>치료 직후·복수 시기에는 강도 조절</li><li>피로·통증 없이 가능한 강도부터</li></ul><p>운동 자체가 종양에 직접 효과는 없지만, 치료를 견디고 회복하는 능력을 좌우합니다.</p>"),
        ("심리적 부담과 일상 회복",
         "<p>진단 직후 우울·불안은 자연스러운 반응입니다.</p><ul><li>가족·친지에게 상황 공유 — 혼자 견디는 것이 가장 위험</li><li>병원의 정신건강의학 협진 가용 — 필요 시 부담 없이</li><li>환자 모임·온라인 커뮤니티 — 정보보다 정서적 지지에 도움</li><li>일상 루틴 유지 — 산책, 가벼운 취미, 사회 활동</li></ul>"),
        ("동반 질환 관리도 멈추지 마세요",
         "<p>당뇨·고혈압·고지혈증의 평소 관리도 그대로 유지합니다.</p><ul><li>당뇨 — 혈당 조절이 간암 예후에 영향. SGLT2/GLP-1은 일부에서 추가 이득</li><li>고혈압 — 면역치료 시 베바시주맙으로 악화 가능, 모니터링</li><li>스타틴 — 일부 연구에서 간암 예방·재발 감소 효과 보고. 자가 중단 금지</li><li>B형/C형 간염 — 항바이러스제 강화·완치 시도</li></ul><p>\"간암이 큰 일이니 다른 약은 일단 멈추자\"라는 결정은 위험합니다. 진료의와 상의해 결정합니다.</p>"),
    ],
    "faq": [
        ("간암에 좋은 음식이 따로 있나요?", "<p>특정 음식이 간암을 작아지게 하지 않습니다. 균형 잡힌 식이와 충분한 단백이 가장 중요합니다.</p>"),
        ("녹용·홍삼은 어떤가요?", "<p>일부 사례에서 간 손상이 보고됩니다. 효과는 검증되지 않았으며 위험-이득 비가 좋지 않습니다.</p>"),
        ("운동을 시작해도 괜찮나요?", "<p>대부분 권장됩니다. 다만 복수가 있거나 심한 피로 시기에는 강도를 줄이세요. 진료의와 상의해 시작 시기를 결정합니다.</p>"),
        ("종교적 단식이 간암에 영향을 주나요?", "<p>장시간 단식은 간경변에서 영양실조·근감소증을 가속화합니다. 종교적 의무가 있다면 진료의와 상의해 조정 방법을 찾습니다.</p>"),
        ("정신적으로 너무 힘든데 약을 먹어도 되나요?", "<p>일부 항우울제·항불안제는 간암·간경변에서 안전합니다. 자가 복용보다 정신건강의학과 협진을 통해 안전한 약을 처방받으세요.</p>"),
    ],
    "refs": [
        ("Plauth M, Bernal W, Dasarathy S, et al. ESPEN guideline on clinical nutrition in liver disease. <em>Clin Nutr</em>. 2019;38(2):485–521.", "10.1016/j.clnu.2018.12.022", "30712783"),
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1–120.", "10.17998/jlc.2022.11.07", None),
        ("Singal AG, Llovet JM, Yarchoan M, et al. AASLD Practice Guidance on prevention, diagnosis, and treatment of hepatocellular carcinoma. <em>Hepatology</em>. 2023;78(6):1922–1965.", "10.1097/HEP.0000000000000466", "37199193"),
        ("Tandon P, Montano-Loza AJ, Lai JC, Dasarathy S, Merli M. Sarcopenia and frailty in decompensated cirrhosis. <em>J Hepatol</em>. 2021;75 Suppl 1:S147–S162.", "10.1016/j.jhep.2021.01.025", "34039486"),
    ],
    "svgs": [
        svg_compare_two("권장 — 일관되게 강조",
                        ["충분한 열량 30–35 kcal/kg",
                         "단백 1.2–1.5 g/kg",
                         "식물성·유제품 단백 우선",
                         "취침 전 야식 200 kcal",
                         "주 150분 가벼운 유산소 + 저항운동",
                         "동반 질환 약 유지·강화"],
                        "회피 — 자주 듣는 위험",
                        ["한약·민간요법 보충제",
                         "녹차 농축 추출물",
                         "출처 불명 \"간 영양제\"",
                         "NSAIDs (이부프로펜 등)",
                         "벤조다이아제핀·진정제",
                         "알코올 (한 잔도 X)"],
                        caption="흔히 \"치료에 도움\"으로 권유받는 것 중 다수가 위험"),
        svg_checklist("진단 후 첫 4주 일상 체크리스트",
                      ["복용 중인 모든 약·영양제·한약 사진으로 정리",
                       "체중·식이·운동 일지 시작",
                       "가족 1명에게 상황 공유, 외래 동반 가능성",
                       "단주 결심·실행 (음주 환자)",
                       "근로 환경·생활 패턴 조정 검토"],
                      caption="첫 4주의 결정이 이후 치료 견디는 능력을 좌우"),
    ],
    "related": [
        ("/간경변-영양-근감소증/", "간경변 영양·근감소증 — 단백 제한은 옛말입니다"),
        ("/간경변-약물-주의/", "간경변 환자가 피해야 할 약·영양제"),
        ("/간암-진단-첫외래/", "간암 진단을 받았을 때, 첫 외래에서 결정되는 것"),
    ],
})

print(f"Series 01 - building {len(ARTICLES)} articles...")
for spec in ARTICLES:
    render_article(spec)
print("Done.")
