"""Series 03 (4) + Series 04 (3) - 7 remaining drafts."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_articles import render_article, svg_table, svg_checklist, svg_compare_two

ARTICLES = []

# 03-6: HBeAg 양성 vs 음성
ARTICLES.append({
    "slug": "B형간염-HBeAg-양성-음성",
    "h1": "HBeAg 양성 vs 음성 — 무엇이 다른가",
    "description": "B형간염의 HBeAg 양성·음성 단계의 자연사 차이, 치료 적응증과 기간의 차이, HBeAg 음성 활동성 간염을 정리합니다.",
    "series_slug": "B형간염", "series_display": "B형 간염", "last_crumb": "HBeAg 양성 vs 음성",
    "section_label": "B형 간염", "about": "만성 B형 간염",
    "tldr": "B형간염은 HBeAg(<em>e항원</em>) 양성·음성에 따라 자연사와 치료 흐름이 다릅니다. 양성은 보통 어릴 때 감염되어 면역관용 → 면역제거 단계를 거치고, 음성은 변이 바이러스로 자연 회복이 드물어 <em>장기 치료가 필요</em>합니다. 같은 \"만성 B형간염\" 환자도 HBeAg 상태에 따라 치료 시작·중단 기준이 다릅니다.",
    "sections": [
        ("HBeAg는 무엇을 의미하나",
         "<p>HBeAg(B형간염 e항원)은 바이러스가 활발히 증식할 때 분비되는 단백입니다. 일반적으로:</p><ul><li>HBeAg 양성 = 바이러스 활동성 ↑, 전염력 ↑</li><li>HBeAg 음성 + anti-HBe 양성 = 바이러스 활동성 ↓ 가능성 있음</li></ul><p>다만 단순한 이분법이 아닙니다. 변이 바이러스(precore mutant)는 HBeAg를 만들지 않으면서도 바이러스 증식이 활발해 \"HBeAg 음성 활동성 간염\"이 됩니다. 따라서 HBeAg 단독으로 치료 결정을 하지 않고 HBV DNA·ALT를 함께 봅니다.</p>"),
        ("자연사 — 4단계 흐름",
         "<p>출생 시 또는 어릴 때 감염된 환자의 일반적 흐름입니다.</p><ol><li><strong>면역관용기</strong> — HBeAg 양성, HBV DNA 매우 높음, ALT 정상. 보통 20대까지.</li><li><strong>면역제거기 (HBeAg 양성 만성 간염)</strong> — ALT 상승, 활동성 간염. 일부에서 HBeAg 혈청전환으로 다음 단계 진입.</li><li><strong>비활동성 보균기</strong> — HBeAg 음성, anti-HBe 양성, HBV DNA 낮음(< 2,000), ALT 정상. 안정적.</li><li><strong>HBeAg 음성 만성 간염</strong> — 변이 바이러스로 ALT·HBV DNA가 다시 오르며 진행성 간염. 자연 회복 드묾.</li></ol><p>한국 환자는 면역제거기·HBeAg 음성 만성 간염 단계에서 진료를 받는 경우가 많습니다.</p>"),
        ("치료 적응증의 차이",
         "<p>두 상태에서 치료 시작 기준이 다릅니다 (KASL 2022).</p><ul><li><strong>HBeAg 양성</strong> — HBV DNA ≥ 20,000 IU/mL + ALT > 정상 상한 2배 이상 (또는 의미 있는 섬유화·간경변)</li><li><strong>HBeAg 음성</strong> — HBV DNA ≥ 2,000 IU/mL + ALT > 정상 상한 2배 이상 (또는 섬유화·간경변)</li></ul><p>HBeAg 음성에서 임계 DNA가 더 낮은 이유는 변이 바이러스가 같은 활동성을 더 낮은 DNA에서도 일으키기 때문입니다.</p>"),
        ("치료 중단 기준의 차이",
         "<p>치료 기간이 두 상태에서 매우 다릅니다.</p><ul><li><strong>HBeAg 양성</strong> — HBeAg 혈청전환(HBeAg 음성 + anti-HBe 양성) 후 HBV DNA 불검출 1년 이상 유지되면 중단 검토 가능. HBsAg 소실이 가장 안전한 중단 시점.</li><li><strong>HBeAg 음성</strong> — 자연 회복이 드물어 <strong>대부분 장기·평생 치료</strong>. HBsAg 소실이 사실상 유일한 중단 신호.</li></ul><p>임의 중단은 두 상태 모두 위험합니다 — 갑작스러운 바이러스 재활성화로 간염 급성악화·간부전 사례가 보고됩니다.</p>"),
        ("\"비활동성 보균자\"는 안전한가",
         "<p>HBeAg 음성 + 낮은 HBV DNA + 정상 ALT 상태입니다. 일반적으로 안정적이지만 다음을 알아야 합니다.</p><ul><li>일부에서 시간이 지나며 변이 바이러스로 활동성 간염 단계로 전환 가능</li><li>간세포암 위험은 0이 아님 — 정기 추적 필수</li><li>면역억제·항암 치료 시 재활성화 위험 있음 — 예방적 항바이러스제 고려</li><li>HBsAg 소실(\"clearance\")까지 기다리는 단계가 아님</li></ul><p>\"비활동성\"이라는 말이 \"안전\"이라는 말은 아닙니다. 6–12개월 간격 추적이 표준입니다.</p>"),
    ],
    "faq": [
        ("HBeAg가 음성이면 전염력이 없나요?", "<p>전염력이 낮긴 하지만 0은 아닙니다. HBV DNA가 검출되면 전염 가능합니다. 가족 검사·백신 권장은 양성·음성과 무관하게 동일합니다.</p>"),
        ("HBeAg가 음성이고 ALT 정상인데 치료해야 하나요?", "<p>HBV DNA가 낮고(< 2,000) 섬유화가 없다면 추적만 합니다. 진행 신호가 보이면 시작합니다.</p>"),
        ("HBeAg 혈청전환이 일어나면 다 나은 건가요?", "<p>아닙니다. 활동성이 줄어든 신호이지만 변이 바이러스로 다시 활동기로 갈 수 있어 추적이 필요합니다.</p>"),
        ("변이 바이러스(precore mutant)가 더 위험한가요?", "<p>HBeAg 음성 만성 간염은 자연 회복이 드물고 진행 위험이 의미 있습니다. \"위험\"이라는 표현보다 \"치료 결정이 다르다\"가 더 정확합니다.</p>"),
        ("두 상태에서 간세포암 위험이 다른가요?", "<p>활동성 간염·간경변·고령·남성·가족력에 따라 결정됩니다. HBeAg 단독으로는 위험 차이를 단정하지 않습니다.</p>"),
    ],
    "refs": [
        ("Korean Association for the Study of the Liver (KASL). KASL clinical practice guidelines for management of chronic hepatitis B. <em>Clin Mol Hepatol</em>. 2022;28(2):276-331.", "10.3350/cmh.2022.0084", None),
        ("Terrault NA, Lok ASF, McMahon BJ, et al. Update on prevention, diagnosis, and treatment of chronic hepatitis B: AASLD 2018 hepatitis B guidance. <em>Hepatology</em>. 2018;67(4):1560-1599.", "10.1002/hep.29800", "29405329"),
        ("European Association for the Study of the Liver. EASL 2017 Clinical Practice Guidelines on the management of hepatitis B virus infection. <em>J Hepatol</em>. 2017;67(2):370-398.", "10.1016/j.jhep.2017.03.021", None),
        ("Funk ML, Rosenberg DM, Lok AS. World-wide epidemiology of HBeAg-negative chronic hepatitis B and associated precore and core promoter variants. <em>J Viral Hepat</em>. 2002;9(1):52-61.", "10.1046/j.1365-2893.2002.00304.x", "11851903"),
    ],
    "svgs": [
        svg_table("HBeAg 단계별 자연사",
                  ["단계", "HBeAg", "HBV DNA", "ALT", "치료"],
                  [["면역관용기", "양성", "매우 높음", "정상", "추적"],
                   ["면역제거기", "양성", "높음", "상승", "기준 충족 시 시작"],
                   ["비활동성 보균기", "음성", "<2,000", "정상", "추적"],
                   ["HBeAg(-) 만성 간염", "음성", "≥2,000", "상승", "장기 치료"]],
                  caption="단계 사이 전환은 시간에 따라 일어남 - 정기 추적이 결정적"),
        svg_compare_two("HBeAg 양성 만성 간염",
                        ["DNA 임계: ≥ 20,000",
                         "ALT 임계: > ULN 2배",
                         "치료 목표: HBeAg 혈청전환",
                         "중단 검토: 전환 + DNA 불검출 1년+",
                         "최종 목표: HBsAg 소실"],
                        "HBeAg 음성 만성 간염",
                        ["DNA 임계: ≥ 2,000 (더 낮음)",
                         "ALT 임계: > ULN 2배",
                         "치료 목표: DNA 억제 유지",
                         "중단 검토: 사실상 HBsAg 소실 시까지",
                         "대부분 장기 치료"],
                        caption="같은 만성 B형간염도 HBeAg 상태로 결정 흐름이 다름"),
    ],
    "related": [
        ("/B형간염-검사결과/", "B형간염 검사 결과지 해석 - HBsAg·HBeAg·anti-HBs"),
        ("/B형간염-평생약/", "B형간염 약을 평생 먹어야 하나요"),
        ("/B형간염-항바이러스제-비교/", "항바이러스제 비교 - TDF · TAF · ETV"),
    ],
})

# 03-7: 항바이러스제 비교 TDF·TAF·ETV
ARTICLES.append({
    "slug": "B형간염-항바이러스제-비교",
    "h1": "B형간염 항바이러스제 비교 - TDF · TAF · ETV",
    "description": "B형간염 1선 항바이러스제 3종(TDF, TAF, 엔테카비르)의 효과·신기능·골밀도·임신·약가 비교와 전환 기준을 정리합니다.",
    "series_slug": "B형간염", "series_display": "B형 간염", "last_crumb": "항바이러스제 비교",
    "section_label": "B형 간염", "about": "만성 B형 간염 치료",
    "tldr": "B형간염 1선 약물 3종은 효과는 비슷하지만 <em>부작용 프로파일</em>이 다릅니다. <em>TDF</em>는 임신 안전성 우수·약가 저렴하나 신·골 부담 가능, <em>TAF</em>는 신·골 안전성 향상, <em>ETV</em>는 라미부딘 미경험자에 강력. 환자의 신기능·골밀도·임신 계획·동반 질환에 따라 선택합니다.",
    "sections": [
        ("3종의 기본 차이",
         "<p>모두 nucleos(t)ide analog 계열로 HBV DNA 폴리머라제를 억제합니다.</p><ul><li><strong>TDF (테노포비르 디소프록실)</strong> - 가장 오래 쓰인 강력한 약물. 신장과 뼈에 일부 부담.</li><li><strong>TAF (테노포비르 알라페나미드)</strong> - TDF의 개선판. 같은 효과 + 신·골 안전성 향상. 약가 더 비쌈.</li><li><strong>ETV (엔테카비르)</strong> - 강력한 효과. 라미부딘 내성에서 효과 떨어짐. 공복 복용 필요.</li></ul><p>3종 모두 내성 발생률이 매우 낮아(< 1% 5년) 1선으로 권장됩니다.</p>"),
        ("효과 비교",
         "<p>임상시험과 실세계 데이터를 종합하면 세 약물의 바이러스 억제 효과는 거의 같습니다.</p><ul><li>1년 후 HBV DNA 불검출률: TDF 약 75–80%, TAF 약 65–75%, ETV 약 70–80%</li><li>5년 후: 90% 이상으로 모두 수렴</li><li>HBeAg 혈청전환: 5년에 약 30–40% (3종 비슷)</li><li>HBsAg 소실: 5년에 약 1–5%로 모두 낮음</li></ul><p>효과보다 환자별 부작용·접근성으로 결정합니다.</p>"),
        ("신기능과 골밀도",
         "<p>세 약물의 가장 큰 임상적 차이입니다.</p><ul><li><strong>TDF</strong> - 일부 환자에서 신기능 저하 (eGFR 감소), 근위세뇨관 손상(Fanconi-like), 골밀도 감소. 흔하진 않지만 장기 복용에서 의미 있음.</li><li><strong>TAF</strong> - 같은 활성 대사물이지만 간세포에 더 선택적으로 농축되어 신·골 노출이 약 90% 적음.</li><li><strong>ETV</strong> - 신기능 영향 적으나 신부전 환자에서 용량 조절 필요.</li></ul><p>신기능 저하·골다공증·고령 환자에서는 TAF 또는 ETV가 선호됩니다. TDF에서 신기능·골밀도 저하가 보이면 TAF 전환이 표준입니다.</p>"),
        ("임신·수유",
         "<p>임신 안전성 데이터는 TDF가 가장 풍부합니다.</p><ul><li><strong>TDF</strong> - HIV·HBV 임신 환자에서 광범위한 사용 데이터, 안전성 확인. HBV DNA가 높은 임산부의 수직감염 차단을 위해 임신 3분기에 사용.</li><li><strong>TAF</strong> - 데이터 누적 중. 일반적으로 안전한 것으로 보고되나 TDF만큼은 아직 아님.</li><li><strong>ETV</strong> - 임신 데이터 제한적. 임신 시 TDF로 전환이 권장.</li></ul><p>수유는 TDF·TAF·ETV 모두 모유로 미량 분비되나 영아에서 의미 있는 노출은 없는 것으로 평가됩니다.</p>"),
        ("전환의 기준",
         "<p>치료 중 약물 전환을 고려하는 상황:</p><ul><li>TDF → TAF: 신기능 저하 (eGFR < 60), 골다공증, 고령, 신독성 약물 동반</li><li>TDF → ETV: 임신 후 또는 다른 부작용</li><li>ETV → TDF: 임신 계획, 라미부딘 내성 의심</li><li>약가 부담: 한국은 TDF가 가장 저렴, TAF가 가장 비쌈 - 보험·본인부담에 따라 결정</li></ul><p>전환은 외래 진료 후 결정하며 자가 변경은 위험합니다.</p>"),
    ],
    "faq": [
        ("TDF에서 TAF로 바꿔야 하나요?", "<p>TDF에서 신기능·골밀도 저하 신호가 있거나 위험 인자(고령, 신독성 약물 동반)가 있으면 검토합니다. 안정적이면 유지해도 됩니다.</p>"),
        ("ETV는 왜 공복 복용하나요?", "<p>음식과 함께 복용 시 흡수가 줄어 효과가 떨어집니다. 식전 2시간 또는 식후 2시간 복용이 표준입니다.</p>"),
        ("3종 외에 다른 옵션은 없나요?", "<p>라미부딘·텔비부딘·아데포비르도 있지만 내성 위험으로 1선이 아닙니다. 페그인터페론은 일부 젊은 환자에서 시도되나 부작용으로 사용이 제한적입니다.</p>"),
        ("약가 차이가 얼마나 되나요?", "<p>한국 보험가는 TDF가 가장 저렴, ETV 중간, TAF가 가장 비쌉니다. 본인부담은 보험 적용·산정특례에 따라 다릅니다.</p>"),
        ("3개월마다 검사받는데 무엇을 보나요?", "<p>HBV DNA, ALT, 빌리루빈, 알부민, 신기능(BUN/Cr/eGFR), 인(P) - 약물 효과·부작용을 동시에 확인합니다.</p>"),
    ],
    "refs": [
        ("Korean Association for the Study of the Liver (KASL). KASL clinical practice guidelines for management of chronic hepatitis B. <em>Clin Mol Hepatol</em>. 2022;28(2):276-331.", "10.3350/cmh.2022.0084", None),
        ("Buti M, Gane E, Seto WK, et al. Tenofovir alafenamide versus tenofovir disoproxil fumarate for the treatment of patients with HBeAg-negative chronic hepatitis B virus infection: a randomised, double-blind, phase 3, non-inferiority trial. <em>Lancet Gastroenterol Hepatol</em>. 2016;1(3):196-206.", "10.1016/S2468-1253(16)30107-8", "28404092"),
        ("Chang TT, Liaw YF, Wu SS, et al. Long-term entecavir therapy results in the reversal of fibrosis/cirrhosis and continued histological improvement in patients with chronic hepatitis B. <em>Hepatology</em>. 2010;52(3):886-893.", "10.1002/hep.23785", "20683932"),
        ("Pan CQ, Duan Z, Dai E, et al. Tenofovir to Prevent Hepatitis B Transmission in Mothers with High Viral Load. <em>N Engl J Med</em>. 2016;374(24):2324-2334.", "10.1056/NEJMoa1508660", "27305192"),
        ("Terrault NA, Lok ASF, McMahon BJ, et al. Update on prevention, diagnosis, and treatment of chronic hepatitis B: AASLD 2018 hepatitis B guidance. <em>Hepatology</em>. 2018;67(4):1560-1599.", "10.1002/hep.29800", "29405329"),
    ],
    "svgs": [
        svg_table("3종 비교 한 표",
                  ["", "TDF", "TAF", "ETV"],
                  [["효과", "강함", "강함", "강함"],
                   ["신기능 부담", "있음 (소수)", "최소", "신부전 시 용량 조정"],
                   ["골밀도", "감소 가능", "최소", "영향 적음"],
                   ["임신 데이터", "가장 풍부", "누적 중", "제한적"],
                   ["복용", "1정/일, 식사 무관", "1정/일, 식사 무관", "공복 (식전·후 2h)"],
                   ["약가", "저렴", "비쌈", "중간"]],
                  caption="효과는 비슷, 환자별 신·골·임신·동반 질환으로 결정"),
        svg_checklist("TDF에서 TAF로 전환을 검토하는 상황",
                      ["eGFR 60 미만으로 떨어졌을 때",
                       "단백뇨·요당이 새로 보임",
                       "골밀도 검사 (DXA)에서 감소 확인",
                       "고령 + 신독성 약물 동반 (NSAIDs, 일부 항생제)",
                       "골다공증·골절 이력"],
                      caption="자가 전환 금지 - 외래에서 평가 후 결정"),
    ],
    "related": [
        ("/B형간염-평생약/", "B형간염 약을 평생 먹어야 하나요"),
        ("/B형간염-HBeAg-양성-음성/", "HBeAg 양성 vs 음성 - 무엇이 다른가"),
        ("/B형간염-검사결과/", "B형간염 검사 결과지 해석"),
    ],
})

# 03-8: B형간염 functional cure
ARTICLES.append({
    "slug": "B형간염-functional-cure",
    "h1": "B형간염 functional cure - 어디까지 와 있나",
    "description": "B형간염의 \"기능적 완치\"(HBsAg 소실) 정의, 현재 표준치료의 한계, siRNA·capsid inhibitor 등 신약 임상의 현 위치를 정리합니다.",
    "series_slug": "B형간염", "series_display": "B형 간염", "last_crumb": "Functional cure",
    "section_label": "B형 간염", "about": "B형 간염 완치",
    "tldr": "B형간염은 현재 항바이러스제로 바이러스를 억제할 수 있지만 완전 박멸은 어렵습니다. <em>HBsAg 소실 + anti-HBs 양전</em>이 임상적 \"기능적 완치(functional cure)\"의 정의이며, 현재 5년 치료에서 약 1–5%만 도달합니다. siRNA, capsid inhibitor, 면역조절제 등 신약 조합이 5년 내 완치율을 30%까지 끌어올리는 것을 목표로 임상시험 중입니다.",
    "sections": [
        ("\"완치\"의 정의가 다른 이유",
         "<p>B형간염은 다른 바이러스 감염과 다릅니다.</p><ul><li>간세포 핵 안에 <strong>cccDNA</strong> 형태로 잠복 - 항바이러스제가 도달 못함</li><li>HBV DNA 억제 후에도 면역억제·항암치료 시 재활성화 가능</li><li>완전 박멸(\"sterilizing cure\")은 현재 불가능</li></ul><p>그래서 \"functional cure\"라는 더 현실적인 목표가 정의되었습니다.</p>"),
        ("Functional cure의 정의와 의미",
         "<p>임상에서 다음을 충족하면 functional cure로 봅니다.</p><ul><li>HBsAg 소실 (혈액 검사에서 음성)</li><li>anti-HBs 양전 (회복 후 면역의 표지)</li><li>치료 중단 후에도 유지</li></ul><p>이 상태가 되면 HBV DNA가 낮은 수준으로 억제되어 간세포암 위험이 의미 있게 감소하고, 사실상 만성 보균자에서 \"회복자\"로 전환됩니다. 다만 cccDNA가 완전히 사라진 것이 아니므로 면역억제 시 재활성화 가능성은 남습니다.</p>"),
        ("현재 표준치료의 한계",
         "<p>현재 항바이러스제(TDF·TAF·ETV)로 functional cure 도달률:</p><ul><li>1년: 약 1%</li><li>5년: 약 3–5%</li><li>10년: 약 5–10%</li></ul><p>도달 가능성을 높이는 인자: 젊은 나이, HBeAg 음성, 낮은 HBsAg quant, 페그인터페론 병용 등. 그러나 대부분의 환자는 평생 항바이러스제 복용을 유지합니다.</p>"),
        ("개발 중인 신약 - 작용 기전별",
         "<p>현재 임상시험 중인 주요 카테고리:</p><ul><li><strong>siRNA</strong> (RNA 간섭) - HBV mRNA를 분해해 모든 바이러스 단백 생산을 차단. JNJ-3989, AB-729 등.</li><li><strong>ASO</strong> (antisense oligonucleotide) - bepirovirsen 등. mRNA 차단의 다른 방식.</li><li><strong>Capsid inhibitor</strong> - 바이러스 캡시드 형성 차단. 일부 단독·조합 시험 중.</li><li><strong>면역조절제</strong> - TLR7/8 작용제, PD-1 차단 등 면역 회복 시도.</li><li><strong>치료적 백신</strong> - 만성 환자의 면역 재교육.</li></ul>"),
        ("임상적 위치와 5–10년 전망",
         "<p>2025년 현재까지 단일 신약으로 functional cure를 의미 있게 끌어올린 사례는 없습니다. 그러나 <strong>siRNA + 면역조절제 + 항바이러스제 3종 병용</strong>이 phase 2에서 HBsAg 소실률을 약 20–30%까지 보고하고 있어, 향후 5–10년 안에 임상 도입 가능성이 있습니다.</p><p>현재 환자가 할 수 있는 것:</p><ul><li>현재 약 잘 복용하며 추적 유지 (자가 중단 절대 금지)</li><li>임상시험 참여 가능성 - 일부 대학병원에서 진행</li><li>새로운 가이드라인·약물 도입 시 진료의와 상의</li></ul>"),
    ],
    "faq": [
        ("HBsAg가 음성으로 바뀌면 약을 끊어도 되나요?", "<p>HBsAg 소실 + anti-HBs 양전이 6–12개월 유지되면 중단을 검토할 수 있습니다. 진료의와 상의해 결정합니다.</p>"),
        ("페그인터페론이 functional cure에 도움된다는데?", "<p>일부 젊은 환자에서 도달률을 높일 수 있지만 부작용(피로, 우울, 백혈구 감소 등)이 커서 모든 환자에 권장되지 않습니다. 신중한 적응증 평가가 필요합니다.</p>"),
        ("임상시험에 참여하려면 어떻게 하나요?", "<p>주요 대학병원 간센터에서 진행됩니다. 진료의에게 본인이 적합한 시험이 있는지 문의할 수 있습니다.</p>"),
        ("functional cure 후에도 재발할 수 있나요?", "<p>드물지만 가능합니다. 면역억제·항암치료 시 재활성화 위험이 있어 그런 치료가 예정되면 예방적 항바이러스제 사용을 검토합니다.</p>"),
        ("HBsAg 정량 검사가 도움이 되나요?", "<p>네. HBsAg quant가 낮을수록(< 1,000 IU/mL) functional cure 도달 가능성이 높습니다. 진행 평가에 점차 활용됩니다.</p>"),
    ],
    "refs": [
        ("Yip TC, Wong GL, Wong VW, et al. Durability of hepatitis B surface antigen seroclearance in untreated and nucleos(t)ide analogue-treated patients. <em>J Hepatol</em>. 2018;68(1):63-72.", "10.1016/j.jhep.2017.09.018", "29107150"),
        ("Yuen MF, Lim SG, Plesniak R, et al. Efficacy and Safety of Bepirovirsen in Chronic Hepatitis B Infection. <em>N Engl J Med</em>. 2022;387(21):1957-1968.", "10.1056/NEJMoa2210027", "36346079"),
        ("Cornberg M, Lok AS, Terrault NA, Zoulim F; 2019 EASL-AASLD HBV Treatment Endpoints Conference Faculty. Guidance for design and endpoints of clinical trials in chronic hepatitis B - Report from the 2019 EASL-AASLD HBV Treatment Endpoints Conference. <em>J Hepatol</em>. 2020;72(3):539-557.", "10.1016/j.jhep.2019.11.003", "31730789"),
        ("Korean Association for the Study of the Liver (KASL). KASL clinical practice guidelines for management of chronic hepatitis B. <em>Clin Mol Hepatol</em>. 2022;28(2):276-331.", "10.3350/cmh.2022.0084", None),
    ],
    "svgs": [
        svg_table("B형간염 \"완치\" 단계 정의",
                  ["단계", "정의", "현재 도달률 (5년)"],
                  [["바이러스 억제", "HBV DNA 불검출", "90%+"],
                   ["HBeAg 혈청전환", "HBeAg 음성 + anti-HBe", "30-40%"],
                   ["Functional cure", "HBsAg 소실 + anti-HBs 양전", "3-5%"],
                   ["Complete cure", "cccDNA까지 박멸", "현재 불가능"]],
                  caption="현재 표준치료의 functional cure 도달률은 낮음"),
        svg_checklist("개발 중인 주요 신약 카테고리",
                      ["siRNA - HBV mRNA 분해 (JNJ-3989, AB-729)",
                       "ASO - antisense oligo (bepirovirsen)",
                       "Capsid inhibitor - 바이러스 캡시드 차단",
                       "면역조절제 - TLR7/8, PD-1 등",
                       "치료적 백신 - 만성 환자 면역 재교육"],
                      caption="단일보다 조합이 향후 임상 도입의 핵심 - phase 2/3 진행 중"),
    ],
    "related": [
        ("/B형간염-평생약/", "B형간염 약을 평생 먹어야 하나요"),
        ("/B형간염-항바이러스제-비교/", "항바이러스제 비교 - TDF · TAF · ETV"),
        ("/B형간염-재활성화/", "항암치료·면역억제제와 B형간염 재활성화"),
    ],
})

# 03-9: 재활성화
ARTICLES.append({
    "slug": "B형간염-재활성화",
    "h1": "항암치료·면역억제제와 B형간염 재활성화",
    "description": "면역억제·항암치료 시 B형간염 재활성화의 위험 분류, 예방적 항바이러스제 적응, 모니터링 일정을 정리합니다.",
    "series_slug": "B형간염", "series_display": "B형 간염", "last_crumb": "재활성화",
    "section_label": "B형 간염", "about": "B형 간염 재활성화",
    "tldr": "면역억제·항암치료를 받는 B형간염 보균자(HBsAg 양성 또는 anti-HBc 양성)는 바이러스 재활성화로 간염 급성악화 위험이 있습니다. <em>치료 시작 전 HBV 검사 + 위험 분류 + 예방적 항바이러스제</em>가 표준입니다. 특히 리툭시맙·고용량 스테로이드·조혈모세포이식이 가장 위험한 카테고리입니다.",
    "sections": [
        ("재활성화는 무엇이고 왜 위험한가",
         "<p>억제되어 있던 HBV가 면역 약화 시 다시 증식하면서 간세포 손상이 일어납니다.</p><ul><li>HBV DNA 1 log 이상 증가 또는 음성에서 검출 전환</li><li>ALT 급등 (보통 3배 이상)</li><li>심하면 간염 급성악화 → 황달 → 간부전</li></ul><p>예방 없이 발생하면 치명률이 높고(특히 리툭시맙 사용 시 사망률 5–25%), 한 번 시작되면 항바이러스제가 늦게 시작될수록 회복이 어렵습니다.</p>"),
        ("위험 분류 - 누가 가장 위험한가",
         "<p>AASLD/KASL 분류 기준 (HBsAg 양성 환자):</p><ul><li><strong>고위험 (재활성화 > 10%)</strong> - 리툭시맙·오비누투주맙(B세포 고갈), 고용량 스테로이드(>20 mg/일 4주+), 조혈모세포이식, 일부 표적치료</li><li><strong>중위험 (1–10%)</strong> - TNF 억제제, 중간 용량 스테로이드, 일부 항암화학</li><li><strong>저위험 (< 1%)</strong> - 단기 저용량 스테로이드, 일부 면역억제</li></ul><p>HBsAg 음성 + anti-HBc 양성 환자도 고위험 약물에서 재활성화 가능 (\"reverse seroconversion\").</p>"),
        ("치료 시작 전 검사 - 모두 해야 하나",
         "<p>면역억제·항암 시작 전 모든 환자에서 다음 검사가 권장됩니다.</p><ul><li>HBsAg</li><li>anti-HBs</li><li>anti-HBc (HBsAg 음성에서도 잠복 감염 검출)</li></ul><p>HBsAg 양성 또는 (HBsAg 음성 + anti-HBc 양성)이면 다음 단계로 갑니다.</p>"),
        ("예방적 항바이러스제",
         "<p>위험에 따라 시작 시점·약물·기간이 결정됩니다.</p><ul><li><strong>HBsAg 양성 + 고/중위험 약물</strong> - 면역억제 시작 1–2주 전 또는 동시에 항바이러스제 시작 (TDF·TAF·ETV 1선)</li><li><strong>HBsAg 음성 + anti-HBc 양성 + 고위험 약물</strong> - 예방적 약물 또는 1–3개월마다 HBsAg/HBV DNA 추적</li><li><strong>중단 시점</strong> - 면역억제 종료 후 6–12개월 (리툭시맙·조혈모세포이식 후엔 12개월 이상)</li><li><strong>중단 후 추적</strong> - 6–12개월 동안 ALT·HBV DNA 매월 - 지연 재활성화 감시</li></ul>"),
        ("이미 시작된 항암 중에 발견되면",
         "<p>드물지 않은 시나리오입니다. 다음을 즉시:</p><ul><li>HBV DNA 정량, ALT 측정</li><li>항바이러스제 즉시 시작 (이상적이지만 가능)</li><li>항암 중단 여부는 종양내과와 상의 - 가능하면 항암 유지가 종양 측면 우선</li><li>간 기능 급격 악화 시 입원</li></ul><p>예방이 가장 좋고, 이미 발생했어도 빠른 항바이러스제 시작이 결과를 좌우합니다.</p>"),
    ],
    "faq": [
        ("백신 맞아서 anti-HBs 양성인데, 그래도 검사해야 하나요?", "<p>anti-HBs 양성·anti-HBc 음성이면 백신 면역으로 보호되어 일반적으로 추가 평가 불필요. anti-HBc도 양성이면 과거 자연 감염력으로 추적이 필요합니다.</p>"),
        ("스테로이드를 단기간만 쓰는데도 약을 먹어야 하나요?", "<p>단기 저용량(< 20 mg/일 < 4주)은 일반적으로 저위험. 그러나 HBsAg 양성에서 반복 사용·고용량 부스트는 위험이 누적될 수 있어 진료의와 상의합니다.</p>"),
        ("리툭시맙 후에 약을 얼마나 더 먹어야 하나요?", "<p>리툭시맙은 B세포 회복까지 12개월 이상 걸려 항바이러스제는 종료 후 최소 12개월, 일부에서 더 오래 유지합니다.</p>"),
        ("자가면역 질환으로 평생 면역억제제를 쓰는데?", "<p>장기 면역억제이면 항바이러스제도 장기·평생 유지가 일반적입니다. HBsAg 음성 + anti-HBc 양성이라도 마찬가지입니다.</p>"),
        ("재활성화가 일어나면 어떤 신호가 나오나요?", "<p>황달, 짙은 갈색 소변, 식욕부진, 우상복부 통증, 극심한 피로. 면역억제 중에 새로 보이면 즉시 ALT·HBV DNA 검사가 필요합니다.</p>"),
    ],
    "refs": [
        ("Reddy KR, Beavers KL, Hammond SP, Lim JK, Falck-Ytter YT; American Gastroenterological Association Institute. American Gastroenterological Association Institute guideline on the prevention and treatment of hepatitis B virus reactivation during immunosuppressive drug therapy. <em>Gastroenterology</em>. 2015;148(1):215-219.", "10.1053/j.gastro.2014.10.039", "25447850"),
        ("Korean Association for the Study of the Liver (KASL). KASL clinical practice guidelines for management of chronic hepatitis B. <em>Clin Mol Hepatol</em>. 2022;28(2):276-331.", "10.3350/cmh.2022.0084", None),
        ("Hwang JP, Feld JJ, Hammond SP, et al. Hepatitis B Virus Screening and Management for Patients With Cancer Prior to Therapy: ASCO Provisional Clinical Opinion Update. <em>J Clin Oncol</em>. 2020;38(31):3698-3715.", "10.1200/JCO.20.01757", "32716741"),
        ("Loomba R, Liang TJ. Hepatitis B Reactivation Associated With Immune Suppressive and Biological Modifier Therapies: Current Concepts, Management Strategies, and Future Directions. <em>Gastroenterology</em>. 2017;152(6):1297-1309.", "10.1053/j.gastro.2017.02.009", "28219691"),
    ],
    "svgs": [
        svg_table("재활성화 위험 분류 (HBsAg 양성)",
                  ["위험", "재활성화율", "대표 약물"],
                  [["고위험", "> 10%", "리툭시맙, 고용량 스테로이드, 조혈모세포이식"],
                   ["중위험", "1-10%", "TNF 억제제, 중간용량 스테로이드, 일부 항암"],
                   ["저위험", "< 1%", "단기 저용량 스테로이드, 일부 면역억제"]],
                  caption="HBsAg 음성 + anti-HBc 양성도 고위험 약물에서 재활성화 가능"),
        svg_checklist("면역억제·항암 시작 전 표준 흐름",
                      ["1. 모든 환자 HBsAg + anti-HBs + anti-HBc 검사",
                       "2. HBsAg 양성 → 위험 분류 → 예방적 항바이러스제 시작",
                       "3. HBsAg 음성·anti-HBc 양성 → 고위험 약물이면 예방 또는 추적",
                       "4. 치료 중 ALT·HBV DNA 1-3개월마다 추적",
                       "5. 면역억제 종료 후 6-12개월 항바이러스제 유지 + 추적"],
                      caption="예방이 가장 결정적 - 이미 발생하면 회복 어려움"),
    ],
    "related": [
        ("/B형간염-평생약/", "B형간염 약을 평생 먹어야 하나요"),
        ("/B형간염-검사결과/", "B형간염 검사 결과지 해석"),
        ("/B형간염-항바이러스제-비교/", "항바이러스제 비교 - TDF · TAF · ETV"),
    ],
})

# 04-7: lean MASLD
ARTICLES.append({
    "slug": "지방간-lean-MASLD",
    "h1": "lean MASLD - 마른 사람의 지방간",
    "description": "정상 BMI에서 발생하는 lean MASLD의 정의, 동양인 cutoff, 위험 인자, 치료 접근의 차이를 정리합니다.",
    "series_slug": "지방간", "series_display": "지방간", "last_crumb": "lean MASLD",
    "section_label": "지방간", "about": "lean MASLD",
    "tldr": "정상 체중 또는 마른 사람에서도 지방간(MASLD)이 약 5–25%에서 발견됩니다 - <em>lean MASLD</em>입니다. 동양인은 BMI 23 미만 또는 25 미만 기준을 쓰며, 인슐린 저항성·복부 비만·유전이 원인. 일반 MASLD와 다른 점은 \"체중 감량 자체가 어려움\"이고, 식이·운동·동반 질환 관리가 핵심입니다.",
    "sections": [
        ("\"마른 사람의 지방간\" - 정의",
         "<p>lean MASLD는 정상 BMI 범위에서 진단된 MASLD입니다. 기준은 인종·지역마다 다릅니다.</p><ul><li>아시아·태평양 - BMI < 23 (lean) 또는 < 25 (non-obese)</li><li>서양 - BMI < 25</li><li>한국 가이드라인 - BMI < 23 + 지방간 영상 + 대사 이상 1가지 이상</li></ul><p>전체 MASLD 환자의 약 10–20%가 lean MASLD에 해당합니다. 동양인이 서양인보다 lean MASLD 비율이 높습니다.</p>"),
        ("왜 마른 사람도 지방간이 생기나",
         "<p>BMI는 정상이지만 다음 인자가 결정적입니다.</p><ul><li><strong>복부 비만 (visceral fat)</strong> - 허리둘레 측정. 한국 남성 90 cm, 여성 85 cm 이상.</li><li><strong>인슐린 저항성</strong> - 정상 체중에서도 가능. 공복혈당·HOMA-IR로 평가.</li><li><strong>지질대사 이상</strong> - 중성지방·HDL 콜레스테롤 패턴.</li><li><strong>유전</strong> - PNPLA3 I148M, TM6SF2 등 변이가 동양인에서 빈도 높음.</li><li><strong>최근 체중 변화</strong> - 빠른 체중 감량·증가.</li><li><strong>특정 식이 패턴</strong> - 과도한 과당·정제 탄수화물.</li></ul>"),
        ("진단과 평가 - 일반 MASLD와 같은가",
         "<p>큰 흐름은 같지만 세부에 차이가 있습니다.</p><ul><li>영상 - 초음파·CT·MRI로 지방간 확인</li><li>비침습 평가 - FIB-4, Fibroscan</li><li>대사 평가 - HbA1c, 지질, 허리둘레, 혈압</li><li>유전적 인자 평가는 임상에서 일상적이지 않으나 가족력 강하면 고려</li></ul><p>주의: lean MASLD에서 실제 섬유화·간경변 위험이 일반 MASLD보다 낮지 않다는 보고도 있어, \"마르니까 괜찮겠지\"라는 안심은 위험합니다.</p>"),
        ("치료 - 무엇이 다른가",
         "<p>일반 MASLD의 \"체중 7–10% 감량\" 권고가 lean MASLD에는 그대로 적용되지 않습니다.</p><ul><li>이미 정상 체중인 환자에서 7–10% 감량은 영양실조·근감소증 위험</li><li>대안: <strong>식이 질 개선 + 운동 + 동반 대사 질환 관리</strong>에 집중</li><li>지중해식 식단, 정제 탄수화물·과당 제한, 운동(특히 근력) 강화</li><li>당뇨·이상지질혈증 동반 시 SGLT2·GLP-1·스타틴 적극 사용</li></ul><p>약물(resmetirom 등)의 효과는 일반 MASLD와 비슷할 것으로 추정되나 lean MASLD 특화 데이터는 적습니다.</p>"),
        ("외래에서 자주 받는 질문",
         "<p>\"마른데 어떻게 지방간이?\" 외래에서 가장 흔한 반응입니다.</p><ul><li>BMI보다 허리둘레·복부 지방이 더 의미</li><li>가족력 - 부모·형제에 비슷한 패턴 있으면 유전 인자 강함</li><li>체중 변화 이력 - 과거 비만 후 감량한 경우 위험 지속</li><li>식이 패턴 - 한국식 \"마르고 정제 탄수화물 많이\" 식이가 흔한 배경</li></ul><p>외래에서 lean MASLD는 \"대사 이상이 있는 마른 사람\"으로 보고 평가합니다.</p>"),
    ],
    "faq": [
        ("BMI가 22인데 지방간이 있을 수 있나요?", "<p>네. 동양인 lean MASLD 기준에 해당하며, 약 10–25%에서 가능합니다.</p>"),
        ("체중을 빼야 하나요? 지금도 마른데?", "<p>이미 정상 체중이면 적극 감량보다 식이 질 개선·운동·근육량 유지가 우선입니다.</p>"),
        ("lean MASLD가 일반 MASLD보다 위험한가요?", "<p>섬유화 진행 위험은 비슷하거나 일부 연구에서 더 높다는 보고도 있습니다. 마르다는 이유로 안심하지 마세요.</p>"),
        ("유전자 검사를 받아야 하나요?", "<p>임상에서 일상적으로 시행되지 않습니다. 가족력이 강하면 고려할 수 있으나 결과가 치료를 크게 바꾸지는 않습니다.</p>"),
        ("간 영양제를 먹어야 하나요?", "<p>검증된 효과 없습니다. 오히려 일부 영양제가 간 손상 원인이 됩니다. 식이·운동이 우선입니다.</p>"),
    ],
    "refs": [
        ("Eslam M, El-Serag HB, Francque S, et al. Metabolic (dysfunction)-associated fatty liver disease in individuals of normal weight. <em>Nat Rev Gastroenterol Hepatol</em>. 2022;19(10):638-651.", "10.1038/s41575-022-00635-5", "35710982"),
        ("Younossi ZM, Stepanova M, Negro F, et al. Nonalcoholic fatty liver disease in lean individuals in the United States. <em>Medicine (Baltimore)</em>. 2012;91(6):319-327.", "10.1097/MD.0b013e3182779d49", "23117851"),
        ("Wong VW, Wong GL, Yeung DK, et al. Incidence of non-alcoholic fatty liver disease in Hong Kong: a population study with paired proton-magnetic resonance spectroscopy. <em>J Hepatol</em>. 2015;62(1):182-189.", "10.1016/j.jhep.2014.08.041", "25195550"),
        ("Rinella ME, Neuschwander-Tetri BA, Siddiqui MS, et al. AASLD Practice Guidance on the clinical assessment and management of nonalcoholic fatty liver disease. <em>Hepatology</em>. 2023;77(5):1797-1835.", "10.1097/HEP.0000000000000323", "36727674"),
    ],
    "svgs": [
        svg_table("Lean MASLD 정의와 빈도",
                  ["지역", "BMI 기준", "MASLD 환자 중 비율"],
                  [["아시아·태평양 (lean)", "< 23", "약 15-25%"],
                   ["아시아·태평양 (non-obese)", "< 25", "약 25-40%"],
                   ["서양 (lean)", "< 25", "약 10-20%"],
                   ["한국 가이드라인", "< 23 + 대사 이상", "약 15-20%"]],
                  caption="동양인은 서양인보다 lean MASLD 비율이 높음"),
        svg_checklist("Lean MASLD에서 평가할 인자",
                      ["허리둘레 (남 90, 여 85 cm 이상이면 복부 비만)",
                       "공복혈당·HbA1c·HOMA-IR (인슐린 저항성)",
                       "중성지방·HDL (지질 패턴)",
                       "혈압 (대사증후군 평가)",
                       "가족력·체중 변화 이력·식이 패턴"],
                      caption="BMI보다 허리둘레와 대사 이상 평가가 결정적"),
    ],
    "related": [
        ("/대사이상지방간-MASLD/", "NAFLD가 MASLD로 바뀐 이유"),
        ("/술-안마셔도-지방간/", "술 안 마시는데 지방간"),
        ("/지방간-치료/", "지방간 치료 - 운동·식이·약물"),
    ],
})

# 04-8: resmetirom과 차세대 약물
ARTICLES.append({
    "slug": "지방간-신약-resmetirom",
    "h1": "지방간 신약 - resmetirom과 다음 세대",
    "description": "MASH 첫 적응증 약물 resmetirom (Rezdiffra)의 임상 위치, 임상시험 중인 GLP-1·survodutide·pemvidutide 등 차세대 약물 정리.",
    "series_slug": "지방간", "series_display": "지방간", "last_crumb": "신약 resmetirom",
    "section_label": "지방간", "about": "MASH 약물치료",
    "tldr": "2024년 미국 FDA가 <em>resmetirom (Rezdiffra)</em>을 MASH 첫 적응증 약물로 승인했습니다. F2-F3 환자에서 NASH 해결과 섬유화 호전을 동시에 보였습니다. 한국은 2026년 현재 보험 미승인. 그 외 GLP-1(세마글루타이드), survodutide, pemvidutide 등 다음 세대가 phase 2/3 진행 중입니다.",
    "sections": [
        ("Resmetirom - 어떤 약인가",
         "<p>간 선택적 갑상선호르몬 수용체 베타(THR-β) 작용제입니다.</p><ul><li>간세포 안의 지방 산화 증가, 신생지방생성 감소</li><li>경구 1정/일</li><li>2024년 3월 FDA 가속 승인 - F2-F3 단계 MASH 첫 적응증 약물</li><li>한국은 2026년 현재 도입·보험 진행 중</li></ul><p>자세한 임상 데이터는 <a href=\"/updates/MAESTRO-NASH-resmetirom-NEJM-2024/\">MAESTRO-NASH 노트</a>에서 다룹니다.</p>"),
        ("임상에서 누구에게 쓰나",
         "<p>FDA 적응증과 임상 위치:</p><ul><li>F2-F3 단계 MASH (조직학적 또는 비침습 평가로 강력히 의심)</li><li>F0-F1은 적응증 외 - 약 부담이 이득보다 큼</li><li>F4 (간경변)은 시험에서 배제 - 효과·안전성 데이터 없음</li><li>한국에서 보험 적용까지는 비보험으로 사용 가능하나 약가 부담 큼</li></ul>"),
        ("다음 세대 - GLP-1과 그 너머",
         "<p>여러 약물이 phase 2/3 진행 중입니다.</p><ul><li><strong>세마글루타이드 (GLP-1)</strong> - ESSENCE 시험 등에서 MASH 해결 효과. NEJM 2025 결과로 적응증 추가 가능성.</li><li><strong>티르제파타이드 (GIP/GLP-1)</strong> - SYNERGY-NASH 등.</li><li><strong>Survodutide (GCG/GLP-1)</strong> - phase 2 결과 양호.</li><li><strong>Pemvidutide (GCG/GLP-1)</strong> - phase 2 진행.</li><li><strong>FGF21 작용제 (efruxifermin)</strong> - 섬유화 호전에 강함.</li></ul><p>각 약물의 적응증·승인 시점은 임상시험 진척에 따라 결정됩니다.</p>"),
        ("기존 약물의 위치",
         "<p>MASH 적응증 외이지만 일부 환자에서 이미 사용되는 약물:</p><ul><li>피오글리타존 - 당뇨·MASH 동반에서 효과. 체중 증가·심부전 위험 주의.</li><li>비타민 E - 비당뇨 NASH에서 일부 효과 보고. 출혈·전립선 위험으로 신중.</li><li>GLP-1 작용제 (세마글루타이드, 둘라글루타이드) - 당뇨·비만 적응증으로 처방되며 MASH에 추가 이득.</li><li>SGLT2 억제제 - 당뇨 적응증, MASH에도 일부 이득.</li></ul>"),
        ("환자 입장에서 알아둘 것",
         "<p>신약 도입은 빠르지만 다음을 기억하세요.</p><ul><li>약물은 \"체중 감량·식이\"의 대체가 아닌 보완</li><li>F2-F3 진행성 환자에서 가장 이득이 큼 - 모든 지방간 환자에 약물이 필요한 것은 아님</li><li>\"기적의 약\"이라는 광고는 회의적으로 - 검증된 약물도 효과는 점진적</li><li>한국 보험 도입 시점은 약물별로 다름 - 진료의와 상의해 결정</li></ul>"),
    ],
    "faq": [
        ("resmetirom을 어디서 받을 수 있나요?", "<p>한국은 2026년 현재 보험 미승인이고 일부 의료기관에서 비보험·연구 목적으로 가능. 진료의에게 문의가 필요합니다.</p>"),
        ("GLP-1 주사가 지방간에 효과 있다는데?", "<p>당뇨·비만 환자에서 체중 감량과 함께 MASH 호전이 보고됩니다. 비당뇨에서의 효과·안전성은 임상시험 진행 중입니다.</p>"),
        ("비타민 E 보충제를 먹어도 되나요?", "<p>고용량 비타민 E (800 IU/일)는 비당뇨 NASH에서 일부 효과 보고. 다만 출혈·전립선암 위험으로 신중히 결정합니다.</p>"),
        ("약을 먹으면 운동·식이를 안 해도 되나요?", "<p>아닙니다. 약은 보완이며 식이·운동이 효과를 결정합니다. 약물 단독은 효과가 절반 이하입니다.</p>"),
        ("F1 단계인데 약을 먹어야 하나요?", "<p>현재 F0-F1에서 MASH 약물의 이득은 명확하지 않습니다. 식이·운동·동반 질환 관리에 집중합니다.</p>"),
    ],
    "refs": [
        ("Harrison SA, Bedossa P, Guy CD, et al. A Phase 3, Randomized, Controlled Trial of Resmetirom in NASH with Liver Fibrosis. <em>N Engl J Med</em>. 2024;390(6):497-509.", "10.1056/NEJMoa2309000", "38324483"),
        ("Newsome PN, Buchholtz K, Cusi K, et al. A Placebo-Controlled Trial of Subcutaneous Semaglutide in Nonalcoholic Steatohepatitis. <em>N Engl J Med</em>. 2021;384(12):1113-1124.", "10.1056/NEJMoa2028395", "33185364"),
        ("Loomba R, Hartman ML, Lawitz EJ, et al. Tirzepatide for Metabolic Dysfunction-Associated Steatohepatitis with Liver Fibrosis. <em>N Engl J Med</em>. 2024;391(4):299-310.", "10.1056/NEJMoa2401943", "38856224"),
        ("Sanyal AJ, Bedossa P, Fraessdorf M, et al. A Phase 2 Randomized Trial of Survodutide in MASH and Fibrosis. <em>N Engl J Med</em>. 2024;391(4):311-319.", "10.1056/NEJMoa2401755", "38856230"),
        ("Rinella ME, Neuschwander-Tetri BA, Siddiqui MS, et al. AASLD Practice Guidance on the clinical assessment and management of nonalcoholic fatty liver disease. <em>Hepatology</em>. 2023;77(5):1797-1835.", "10.1097/HEP.0000000000000323", "36727674"),
    ],
    "svgs": [
        svg_table("MASH 약물 - 현재와 임상시험",
                  ["약물", "기전", "단계"],
                  [["Resmetirom", "THR-β 작용제", "FDA 승인 (2024) - F2-F3"],
                   ["Semaglutide", "GLP-1", "Phase 3 (ESSENCE)"],
                   ["Tirzepatide", "GIP/GLP-1", "Phase 2/3"],
                   ["Survodutide", "GCG/GLP-1", "Phase 2"],
                   ["Efruxifermin", "FGF21 작용제", "Phase 2/3"]],
                  caption="2024-2025년 다수 phase 2/3 결과 발표 - 향후 5년 약물 지형 변화 큼"),
        svg_checklist("MASH 약물치료 적응증 (resmetirom 기준)",
                      ["F2-F3 단계 MASH (조직 또는 비침습)",
                       "체중 감량·식이만으로 진행 시 추가 고려",
                       "F0-F1: 약물보다 생활 관리 우선",
                       "F4 간경변: 데이터 부족 - 합병증 관리 우선",
                       "비용·접근성 평가 (한국 비보험)"],
                      caption="\"진행성 MASH\"가 약물치료의 핵심 적응증"),
    ],
    "related": [
        ("/지방간염-MASH/", "지방간염(MASH) - 단순 지방간과 무엇이 다른가"),
        ("/지방간-치료/", "지방간 치료 - 운동·식이·약물"),
        ("/지방간-SGLT2-GLP1/", "SGLT2·GLP-1 작용제와 지방간"),
    ],
})

# 04-10: SGLT2·GLP-1
ARTICLES.append({
    "slug": "지방간-SGLT2-GLP1",
    "h1": "SGLT2·GLP-1 작용제와 지방간",
    "description": "당뇨 약물인 SGLT2 억제제와 GLP-1 작용제가 지방간(MASLD)에 어떤 효과를 보이는가, 비당뇨 환자에서의 위치를 정리합니다.",
    "series_slug": "지방간", "series_display": "지방간", "last_crumb": "SGLT2·GLP-1",
    "section_label": "지방간", "about": "MASLD 동반 당뇨 치료",
    "tldr": "당뇨약인 SGLT2 억제제와 GLP-1 작용제가 <em>지방간 호전·체중 감량·심혈관 보호</em> 효과를 함께 보여 MASLD에서 적극 사용됩니다. 당뇨 동반 환자에서는 1차 옵션 중 하나, 비당뇨 환자에서는 비만·심혈관 위험이 높을 때 검토됩니다.",
    "sections": [
        ("SGLT2 억제제 - 어떻게 작동하나",
         "<p>신장에서 포도당 재흡수를 억제해 소변으로 배설시키는 약물입니다. 다파글리플로진·엠파글리플로진 등.</p><ul><li>혈당 강하 (당뇨)</li><li>체중 감량 약 2-3 kg</li><li>심부전 위험 감소</li><li>신장 보호</li><li>지방간 - 간 지방량 감소, ALT 감소, 일부에서 섬유화 호전</li></ul><p>당뇨 환자의 약 10-15%에서 1년 내 지방간 호전이 보고됩니다.</p>"),
        ("GLP-1 작용제 - 강력한 체중 감량",
         "<p>장내 GLP-1 호르몬 작용을 모방해 인슐린 분비 증가, 식욕 억제, 위 배출 지연 효과를 냅니다. 세마글루타이드(오젬픽·위고비)·둘라글루타이드 등.</p><ul><li>혈당 강하</li><li>체중 감량 5-15% (용량·기간에 따라)</li><li>심혈관 사건 감소</li><li>지방간 - NASH 해결률 위약 대비 의미 있게 높음 (NEJM 2021 Newsome)</li></ul><p>현재까지 가장 강력한 비-MASH 약물. ESSENCE 시험 결과로 MASH 적응증 추가 가능성이 있습니다.</p>"),
        ("당뇨 동반 MASLD 환자에서 1차로 고려되는 이유",
         "<p>전통적인 메트포르민도 1차이지만, 다음 환자에서는 SGLT2/GLP-1을 우선합니다.</p><ul><li>비만 동반 (BMI ≥ 30, 동양인 ≥ 27)</li><li>심혈관 질환 또는 심부전</li><li>만성 신장 질환 (SGLT2가 특히 유리)</li><li>MASH 진행 또는 섬유화 의심</li></ul><p>한국 임상에서도 당뇨·비만·MASLD 동반 환자에서 두 약물 사용이 빠르게 증가합니다.</p>"),
        ("비당뇨 환자에서의 위치",
         "<p>적응증·보험·임상 위치가 다릅니다.</p><ul><li>비당뇨 + 비만 + MASH - GLP-1(고용량 세마글루타이드 \"위고비\")이 비만 적응증으로 사용 가능</li><li>비당뇨에서 SGLT2의 MASLD 효과는 제한적 데이터</li><li>약가 부담이 큼 (비보험)</li><li>약물보다 식이·운동이 우선 권장</li></ul>"),
        ("부작용과 주의",
         "<p>두 약물의 흔한 부작용:</p><ul><li><strong>SGLT2</strong> - 요로 감염, 외음부 감염, 케토산증(드물지만 위험), 탈수, 저혈당 (인슐린 동반 시)</li><li><strong>GLP-1</strong> - 구역·구토·설사 (시작·증량 시), 췌장염 (드물게), 갑상선 종양 (동물 모델, 인간 미확정)</li><li>두 약물 모두 임신 시 일반적으로 회피</li><li>위장관 부작용은 천천히 증량으로 완화 가능</li></ul>"),
    ],
    "faq": [
        ("당뇨가 없는데 GLP-1 주사를 맞아도 되나요?", "<p>비만 적응증으로 위고비(고용량 세마글루타이드)가 처방됩니다. 비당뇨에서 보험 미적용으로 약가 부담이 큽니다.</p>"),
        ("SGLT2와 GLP-1을 동시에 쓸 수 있나요?", "<p>일부 환자(당뇨 + 심혈관 위험 + 비만)에서 함께 쓰며 효과가 더해집니다. 약가·접근성을 고려해 결정.</p>"),
        ("이 약을 시작하면 메트포르민을 끊나요?", "<p>대부분 메트포르민과 함께 씁니다. 강력한 당뇨 조절을 위해 조합 사용이 표준입니다.</p>"),
        ("간경변 환자도 쓸 수 있나요?", "<p>대상성 간경변에서 사용 사례가 있으나 비대상성에서는 제한적. 진료의와 상의해 결정.</p>"),
        ("주사보다 먹는 약이 있나요?", "<p>먹는 세마글루타이드(리벨서스)가 있지만 식전 30분 공복 복용·물 한 모금만 등 복용법이 까다롭습니다.</p>"),
    ],
    "refs": [
        ("Newsome PN, Buchholtz K, Cusi K, et al. A Placebo-Controlled Trial of Subcutaneous Semaglutide in Nonalcoholic Steatohepatitis. <em>N Engl J Med</em>. 2021;384(12):1113-1124.", "10.1056/NEJMoa2028395", "33185364"),
        ("Kahl S, Gancheva S, Straßburger K, et al. Empagliflozin Effectively Lowers Liver Fat Content in Well-Controlled Type 2 Diabetes. <em>Diabetes Care</em>. 2020;43(2):298-305.", "10.2337/dc19-0641", "31540903"),
        ("Mantovani A, Petracca G, Beatrice G, et al. Glucagon-Like Peptide-1 Receptor Agonists for Treatment of Nonalcoholic Steatohepatitis: Systematic Review and Meta-Analysis of Randomized Controlled Trials. <em>Metabolites</em>. 2021;11(2):73.", "10.3390/metabo11020073", "33530433"),
        ("Rinella ME, Neuschwander-Tetri BA, Siddiqui MS, et al. AASLD Practice Guidance on the clinical assessment and management of nonalcoholic fatty liver disease. <em>Hepatology</em>. 2023;77(5):1797-1835.", "10.1097/HEP.0000000000000323", "36727674"),
        ("ElSayed NA, Aleppo G, Aroda VR, et al. 9. Pharmacologic Approaches to Glycemic Treatment: Standards of Care in Diabetes-2023. <em>Diabetes Care</em>. 2023;46(Suppl 1):S140-S157.", "10.2337/dc23-S009", "36507650"),
    ],
    "svgs": [
        svg_compare_two("SGLT2 억제제",
                        ["다파글리플로진·엠파글리플로진",
                         "체중 감량 2-3 kg",
                         "심부전·신장 보호 효과",
                         "지방량·ALT 감소",
                         "부작용: 요로 감염·케토산증"],
                        "GLP-1 작용제",
                        ["세마글루타이드·둘라글루타이드",
                         "체중 감량 5-15%",
                         "심혈관 사건 감소",
                         "MASH 해결 효과 (NEJM 2021)",
                         "부작용: 구역·구토 (증량으로 완화)"],
                        caption="당뇨 동반 MASLD 환자에서 1차 옵션 - 환자 상황에 따라 선택"),
        svg_table("당뇨 동반 MASLD 1차 약물 선택",
                  ["환자 특성", "권장 옵션"],
                  [["비만 + MASH 의심", "GLP-1 (세마글루타이드 등)"],
                   ["심부전 동반", "SGLT2 (다파/엠파)"],
                   ["만성 신장 질환", "SGLT2 우선"],
                   ["둘 다 적응", "조합 사용 검토"],
                   ["체중 정상 + 단순 당뇨", "메트포르민 + DPP-4 또는 SU"]],
                  caption="환자별 동반 질환·체중·신장 상태로 결정"),
    ],
    "related": [
        ("/지방간-치료/", "지방간 치료 - 운동·식이·약물"),
        ("/지방간-신약-resmetirom/", "지방간 신약 - resmetirom과 다음 세대"),
        ("/지방간염-MASH/", "지방간염(MASH)"),
    ],
})

print(f"Series 03+04 - building {len(ARTICLES)} articles...")
for spec in ARTICLES:
    render_article(spec)
print("Done.")
