"""Series 05 (간수치) - 5 new articles."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_articles import render_article, svg_table, svg_checklist, svg_compare_two

ARTICLES = []

# 05-5: 알부민·PT
ARTICLES.append({
    "slug": "알부민-PT-간합성능",
    "h1": "알부민·PT(INR) - 간의 합성능을 보는 두 수치",
    "description": "간세포 손상보다 간 합성능 저하를 더 직접적으로 보는 두 수치 - 알부민과 PT(INR)의 의미, 임상 패턴, Child-Pugh·MELD에서의 역할.",
    "series_slug": "간수치", "series_display": "간수치 이상", "last_crumb": "알부민·PT",
    "section_label": "간수치", "about": "간 합성능 저하",
    "tldr": "AST·ALT는 간세포가 \"손상되었다\"를 보여주고, <em>알부민·PT</em>는 간이 \"제 기능을 하나\"를 봅니다. 알부민은 반감기가 약 3주로 만성 변화에, PT는 반감기가 짧아 급성 변화에 민감합니다. 두 수치 모두 Child-Pugh·MELD의 핵심 구성요소입니다.",
    "sections": [
        ("간 합성능이 무엇인가",
         "<p>간의 주된 역할 중 하나가 단백 합성입니다.</p><ul><li>알부민 - 가장 풍부한 혈청 단백, 간에서만 생성</li><li>응고 인자 (II, V, VII, IX, X) - PT/INR로 측정</li><li>기타 (haptoglobin, transferrin 등)</li></ul><p>간세포가 죽으면 효소(AST·ALT)가 새어나오지만, 간세포가 적게 살아있으면 합성이 줄어들어 알부민·응고 인자가 떨어집니다. 진행된 간경변에서 효소는 정상이어도 합성이 떨어진 패턴이 흔합니다.</p>"),
        ("알부민 - 만성 변화의 거울",
         "<p>알부민의 특성:</p><ul><li>정상 범위: 3.5–5.0 g/dL</li><li>반감기 약 20일 - <strong>만성 변화에 민감</strong>, 급성에는 둔감</li><li>간경변 진행 시 점진적 감소</li><li>단백뇨·영양실조·염증으로도 떨어짐 (간 외 원인)</li></ul><p>알부민이 3.5 미만이면 의미 있는 합성능 저하 신호이며, 2.8 미만은 진행된 간경변·심한 영양실조를 시사합니다. Child-Pugh 점수의 한 항목이며, 이뇨제 반응·복수 관리에도 직접 영향을 줍니다.</p>"),
        ("PT/INR - 급성 변화의 거울",
         "<p>응고 인자들의 종합 지표입니다.</p><ul><li>정상: PT 11–13초, INR 0.9–1.1</li><li>반감기 짧음 (인자 VII는 6시간) - <strong>급성 변화에 민감</strong></li><li>비타민 K 결핍에서도 상승 (담도 폐쇄·항생제·영양실조)</li><li>와파린·신규 항응고제 복용 시 별도 해석</li></ul><p>비타민 K 보충 후에도 PT가 회복 안 되면 간 합성능 저하로 봅니다. 급성 간부전에서 INR 상승이 가장 빠른 신호 중 하나입니다.</p>"),
        ("두 수치를 함께 보는 패턴",
         "<p>임상 패턴을 정리하면:</p><ul><li><strong>둘 다 정상</strong> - 간 합성능 보존</li><li><strong>알부민 ↓ + PT 정상</strong> - 만성 변화 또는 단백뇨·영양실조 (간 외 원인 가능)</li><li><strong>알부민 정상 + PT ↑</strong> - 급성 변화 또는 비타민 K 결핍·항응고제</li><li><strong>둘 다 ↓</strong> - 진행된 간 합성능 저하 또는 비대상성 간경변</li></ul><p>한 수치만 보면 오해할 수 있고, 다른 검사(AST/ALT, 빌리루빈, 영상)와 함께 해석합니다.</p>"),
        ("Child-Pugh와 MELD에서의 역할",
         "<p>두 수치 모두 임상 점수의 핵심 구성요소입니다.</p><ul><li><strong>Child-Pugh</strong> - 알부민과 PT가 5개 항목 중 2개</li><li><strong>MELD</strong> - INR이 3개 인자 중 하나 (빌리루빈·INR·크레아티닌)</li><li><strong>MELD 3.0</strong> - 알부민이 추가 보정 인자로 들어감</li></ul><p>이 수치 변화로 환자의 단계·이식 우선순위가 바뀌므로 정기 추적이 결정적입니다.</p>"),
    ],
    "faq": [
        ("알부민이 3.0인데 위험한가요?", "<p>의미 있는 감소이지만 해석은 맥락에 따라. 간 외 원인(단백뇨·영양실조·심부전)을 함께 평가합니다.</p>"),
        ("간경변인데 알부민이 정상이면 안심해도 되나요?", "<p>대상성 단계라는 신호이지만, 영상·다른 수치(빌리루빈·PT·혈소판)와 함께 봐야 합니다.</p>"),
        ("PT 검사 받기 전에 비타민이 든 음식 먹어도 되나요?", "<p>일반 식사는 검사에 영향 거의 없습니다. 비타민 K 보충제는 의사와 상의.</p>"),
        ("INR 1.5인데 와파린 안 먹는데도?", "<p>간 합성능 저하 또는 비타민 K 결핍 가능. 다른 간 검사와 함께 평가합니다.</p>"),
        ("알부민 보충제(주사)를 맞으면 수치가 좋아지나요?", "<p>일시적으로 수치는 오르지만 근본 원인 치료가 아닙니다. 복수·SBP 등 특정 상황에서만 표준 적응증.</p>"),
    ],
    "refs": [
        ("Kwo PY, Cohen SM, Lim JK. ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries. <em>Am J Gastroenterol</em>. 2017;112(1):18-35.", "10.1038/ajg.2016.517", "27995906"),
        ("Garcia-Tsao G, Friedman S, Iredale J, Pinzani M. Now there are many (stages) where before there was one: In search of a pathophysiological classification of cirrhosis. <em>Hepatology</em>. 2010;51(4):1445-1449.", "10.1002/hep.23478", "20077563"),
        ("Tripodi A, Mannucci PM. The coagulopathy of chronic liver disease. <em>N Engl J Med</em>. 2011;365(2):147-156.", "10.1056/NEJMra1011170", "21751907"),
        ("Korean Association for the Study of the Liver. KASL clinical practice guidelines for liver cirrhosis. <em>Clin Mol Hepatol</em>. 2020;26(2):83-127.", "10.3350/cmh.2019.0010n", None),
    ],
    "svgs": [
        svg_table("알부민과 PT 비교",
                  ["", "알부민", "PT/INR"],
                  [["정상 범위", "3.5-5.0 g/dL", "PT 11-13s / INR 0.9-1.1"],
                   ["반감기", "약 20일", "수시간-1일"],
                   ["변화 민감도", "만성", "급성"],
                   ["간 외 원인", "단백뇨·영양실조·염증", "비타민 K 결핍·항응고제"],
                   ["임상 점수", "Child-Pugh, MELD 3.0", "Child-Pugh, MELD"]],
                  caption="두 수치는 보완 관계 - 함께 봐야 정확한 해석"),
        svg_checklist("간 합성능 저하의 흔한 패턴",
                      ["둘 다 정상 = 보존",
                       "알부민↓ + PT 정상 = 만성 또는 간 외 원인",
                       "알부민 정상 + PT↑ = 급성 또는 비타민 K 결핍",
                       "둘 다↓ = 진행된 간 합성능 저하·비대상성",
                       "알부민 < 2.8 또는 INR > 1.7 = 진행 간경변 신호"],
                      caption="다른 간 수치·영상과 함께 종합 해석"),
    ],
    "related": [
        ("/간수치-높음/", "건강검진 간수치(AST·ALT) 높음"),
        ("/간수치-종류-차이/", "AST · ALT · GGT 차이"),
        ("/간경변-Child-Pugh-MELD/", "Child-Pugh와 MELD"),
    ],
})

# 05-6: ALP·GGT
ARTICLES.append({
    "slug": "ALP-GGT-담도-간세포",
    "h1": "ALP · GGT - 담도 막힘 vs 간세포 손상을 가르는 두 수치",
    "description": "ALP와 GGT의 출처, 두 수치를 함께 봐서 담도성과 간세포성을 어떻게 가르나, 임상 패턴별 해석을 정리합니다.",
    "series_slug": "간수치", "series_display": "간수치 이상", "last_crumb": "ALP·GGT",
    "section_label": "간수치", "about": "담도 효소",
    "tldr": "ALP와 GGT는 함께 오를 때 <em>담도 또는 담즙 정체</em>를 의심합니다. ALP만 오르고 GGT 정상이면 뼈·태반 같은 비간성 원인을, GGT 단독 상승은 알코올·약물·일부 비만에서 흔합니다. AST/ALT와 함께 패턴으로 봐야 진단 방향이 명확해집니다.",
    "sections": [
        ("ALP는 어디서 오나",
         "<p>ALP(alkaline phosphatase)는 여러 조직에 있습니다.</p><ul><li>간 - 담관 세포에 풍부</li><li>뼈 - 골세포에서 분비, 성장기 아동·골 회복 시 상승</li><li>태반 - 임신 후반기 상승</li><li>장 - 일부 기여</li></ul><p>혈액의 ALP가 올랐을 때 \"간 ALP인지 뼈 ALP인지\"를 가르는 것이 첫 단계입니다. ALP isoenzyme 분석이 가장 정확하지만, 임상에서는 <strong>GGT를 함께 보는</strong> 방법이 빠릅니다.</p>"),
        ("GGT는 무엇을 의미하나",
         "<p>GGT(γ-glutamyl transferase)는 간 외에는 거의 없는 효소입니다.</p><ul><li>간·담도 - 주된 출처</li><li>알코올·약물 유발 효소 (\"inducible enzyme\")</li><li>비만·당뇨·MASLD에서 만성 상승</li><li>심혈관 위험과도 약한 연관</li></ul><p>GGT는 매우 민감하지만 비특이적입니다. 거의 모든 간·담도 질환에서 오를 수 있어 \"간이 어디 잘못됐다\"의 첫 단서지만 단독으로 진단하지 않습니다.</p>"),
        ("두 수치를 함께 보는 패턴",
         "<p>임상 패턴은 다음과 같습니다.</p><ul><li><strong>ALP↑ + GGT↑</strong> - 담도성 (담즙 정체, 담관 폐쇄, 담즙성 간 질환). 간성 ALP임을 GGT가 확인.</li><li><strong>ALP↑ + GGT 정상</strong> - 비간성 (뼈, 임신, 성장기). 간 검사 추가 평가 보통 불필요.</li><li><strong>ALP 정상 + GGT↑</strong> - 알코올, 약물 유도, 일부 MASLD, 일부 담도 초기.</li></ul><p>여기에 빌리루빈·AST·ALT를 더해 더 정확한 패턴을 만듭니다.</p>"),
        ("AST/ALT와의 조합 패턴",
         "<p>큰 그림을 잡는 4가지 패턴:</p><ul><li><strong>간세포성</strong> - AST·ALT↑↑, ALP·GGT 경증 (바이러스성·약물성·알코올성 간염)</li><li><strong>담도성</strong> - ALP·GGT↑↑, AST·ALT 경증 (담석, 담관암, PBC, PSC)</li><li><strong>혼합형</strong> - 둘 다 의미 있게 상승 (약물성·바이러스성 일부)</li><li><strong>R 비율</strong> = (ALT/ULN) ÷ (ALP/ULN). > 5 간세포성, < 2 담도성, 2-5 혼합</li></ul>"),
        ("외래에서 결정되는 다음 단계",
         "<p>패턴에 따라 추가 검사가 다릅니다.</p><ul><li>담도성 의심 - 복부 초음파 → MRCP/EUS, 자가항체 (AMA - PBC, ANCA - PSC)</li><li>간세포성 - B/C형 바이러스, 약물 점검, 자가면역 패널</li><li>GGT 단독 상승 - 음주력, 약물 점검, MASLD 평가</li><li>ALP 단독 상승 - 뼈 영상, 비타민 D, 임신 여부</li></ul>"),
    ],
    "faq": [
        ("GGT만 100인데 술을 끊으면 떨어지나요?", "<p>알코올성이라면 보통 2-4주에 의미 있게 떨어집니다. 다른 원인 동반 시 회복 패턴이 다를 수 있습니다.</p>"),
        ("ALP가 높은데 임신 중이에요. 간 검사 더 받아야 하나요?", "<p>임신 후반기 태반성 ALP 상승은 정상. GGT가 정상이면 추가 평가 불필요. 산과·간 진료의 함께 평가합니다.</p>"),
        ("아이 ALP가 높다는데 위험한가요?", "<p>성장기 아동의 골 ALP 상승은 정상. GGT가 정상이면 간 문제 아님.</p>"),
        ("비만인데 GGT가 항상 높아요.", "<p>MASLD·인슐린 저항성에서 흔한 패턴. 체중 감량으로 호전됩니다. 다른 검사로 진행성 평가가 필요.</p>"),
        ("ALP·GGT 둘 다 높은데 담석이 없어요.", "<p>PBC, PSC, 약물성 담즙 정체, 일부 종양 등 다른 원인을 평가합니다. MRCP·자가항체·약물 점검이 다음 단계.</p>"),
    ],
    "refs": [
        ("Kwo PY, Cohen SM, Lim JK. ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries. <em>Am J Gastroenterol</em>. 2017;112(1):18-35.", "10.1038/ajg.2016.517", "27995906"),
        ("European Association for the Study of the Liver. EASL Clinical Practice Guidelines on the management of cholestatic liver diseases. <em>J Hepatol</em>. 2009;51(2):237-267.", "10.1016/j.jhep.2009.04.009", None),
        ("Newsome PN, Cramb R, Davison SM, et al. Guidelines on the management of abnormal liver blood tests. <em>Gut</em>. 2018;67(1):6-19.", "10.1136/gutjnl-2017-314924", "29122851"),
        ("Whitfield JB. Gamma glutamyl transferase. <em>Crit Rev Clin Lab Sci</em>. 2001;38(4):263-355.", "10.1080/20014091084227", "11563810"),
    ],
    "svgs": [
        svg_table("ALP·GGT 패턴 해석",
                  ["ALP", "GGT", "의미"],
                  [["↑↑", "↑↑", "담도성 (담석, 담관암, PBC, PSC)"],
                   ["↑↑", "정상", "비간성 (뼈, 임신, 성장기)"],
                   ["정상", "↑↑", "알코올, 약물 유도, MASLD, 초기 담도"],
                   ["정상", "정상", "특별한 소견 없음"]],
                  caption="ALP가 \"간성인지\"를 GGT로 빠르게 확인"),
        svg_table("R 비율로 분류",
                  ["R = (ALT/ULN) ÷ (ALP/ULN)", "분류", "의심 원인"],
                  [["> 5", "간세포성", "바이러스, 약물, 알코올, 자가면역"],
                   ["2 - 5", "혼합형", "약물성 일부, 바이러스 회복기"],
                   ["< 2", "담도성", "담석, 담관암, PBC, PSC"]],
                  caption="DILI(약물성 간 손상) 분류에도 사용되는 표준 비율"),
    ],
    "related": [
        ("/간수치-높음/", "건강검진 간수치(AST·ALT) 높음"),
        ("/간수치-종류-차이/", "AST · ALT · GGT 차이"),
        ("/빌리루빈-직접-간접/", "빌리루빈 - 직접·간접 차이"),
    ],
})

# 05-7: 약물·영양제·한약 간 손상
ARTICLES.append({
    "slug": "약물성-간손상-DILI",
    "h1": "약물·영양제·한약 - 간 손상 가능성 점검",
    "description": "약물성 간 손상(DILI)의 흔한 원인 약물, 한약·건강기능식품의 위험, 외래에서 점검하는 방법, 의심 시 대응을 정리합니다.",
    "series_slug": "간수치", "series_display": "간수치 이상", "last_crumb": "약물성 간 손상",
    "section_label": "간수치", "about": "약물성 간 손상",
    "tldr": "약물성 간 손상(DILI)은 외래 간수치 이상의 흔한 원인입니다. 한국에서는 <em>한약·건강기능식품이 DILI의 30-40%</em>를 차지해 처방약보다도 흔합니다. 의심되면 <em>의심 약물 즉시 중단 + 다른 원인 배제</em>가 첫 단계입니다.",
    "sections": [
        ("DILI는 무엇이고 얼마나 흔한가",
         "<p>약물·한약·영양제 등이 간세포·담도에 손상을 주는 현상입니다.</p><ul><li>한국 외래 ALT 상승 원인의 약 10-15%</li><li>한국은 한약·건강기능식품 비율이 높아 DILI 원인 분포가 서양과 다름</li><li>대부분 약 중단 후 회복하지만 5-10%에서 만성화·간이식 필요</li></ul>"),
        ("처방약 - 흔한 원인",
         "<p>외래에서 자주 만나는 처방 약물:</p><ul><li>아세트아미노펜 - 과량 복용 (한 번에 7.5g 이상 또는 만성 4g/일 이상)</li><li>항생제 - amoxicillin/clavulanate, isoniazid (결핵약), 일부 macrolide</li><li>NSAIDs - ibuprofen, diclofenac</li><li>스타틴 - 일반적으로 안전하나 일부에서 ALT 상승</li><li>항암제 - 다양한 약물</li><li>면역억제제·항진균제 - methotrexate, azathioprine, ketoconazole</li></ul>"),
        ("한약·건강기능식품 - 한국에서 가장 흔한 원인",
         "<p>한국 DILI의 30-40%를 차지하는 카테고리입니다.</p><ul><li>한약재 - 백선, 하수오, 유근피, 인진쑥 등 보고 사례</li><li>녹차 농축 추출물 (catechin 농축 보충제) - 급성 간염 사례</li><li>'간에 좋다'는 영양제 - 검증되지 않은 성분</li><li>가르시니아·녹용·관절 영양제 일부</li><li>운동 보조제 (anabolic steroid 함유 일부)</li></ul><p>환자가 \"이건 약이 아니라 천연이다\"라고 인식해 외래에 보고하지 않는 경우가 가장 위험합니다.</p>"),
        ("패턴별 분류 - 진단의 단서",
         "<p>DILI의 임상 패턴은 R 비율로 분류합니다.</p><ul><li>간세포성 (R > 5) - ALT↑↑ - 바이러스 간염과 유사 (isoniazid, methotrexate, 일부 한약)</li><li>담도성 (R < 2) - ALP↑↑ - 담즙 정체 패턴 (amoxicillin/clavulanate, anabolic steroid)</li><li>혼합형 (R 2-5) - 둘 다 - 일부 항생제·NSAIDs</li></ul><p>각 약물의 전형 패턴이 알려져 있어 패턴이 의심 약물을 좁히는 데 도움이 됩니다.</p>"),
        ("의심되면 - 다음 단계",
         "<p>DILI 의심 시 표준 흐름:</p><ul><li>1. 의심 약물 즉시 중단 (가장 결정적)</li><li>2. 다른 원인 배제 - 바이러스성(B/C/A형), 자가면역, 알코올, 영상 (담도)</li><li>3. RUCAM score - 인과관계 평가 도구</li><li>4. 1-2주 후 재검 - 호전 확인</li><li>5. 회복 안 되면 입원·간 생검 고려</li><li>6. 같은 약 재투여는 일반적으로 금지 (re-challenge severity 위험)</li></ul>"),
    ],
    "faq": [
        ("녹차를 마셔도 안 좋은가요?", "<p>일반 녹차 음용은 보통 안전. catechin 농축 보충제(녹차 추출물)가 일부에서 급성 간염을 유발한 보고가 있습니다.</p>"),
        ("타이레놀을 매일 먹는데 괜찮나요?", "<p>하루 4 g 이내, 알코올 동반 시 2 g 이내가 안전 범위. 그 이상 만성 복용은 간 손상 위험.</p>"),
        ("한약을 처방받았는데 어떻게 점검하나요?", "<p>한약 처방전·복용 사진을 외래에 가져와 진료의에게 보여주세요. 1-3개월 시점 ALT 추적이 권장됩니다.</p>"),
        ("DILI에서 회복하면 같은 약을 다시 먹어도 되나요?", "<p>일반적으로 권장되지 않습니다. 재투여 시 더 심한 손상이 보고됩니다.</p>"),
        ("간에 좋은 영양제가 정말 없나요?", "<p>현재까지 \"간에 좋다\"는 명확히 입증된 영양제는 없습니다. 식이·운동·체중 관리가 가장 강력한 \"영양 처방\"입니다.</p>"),
    ],
    "refs": [
        ("Chalasani NP, Maddur H, Russo MW, Wong RJ, Reddy KR. ACG Clinical Guideline: Diagnosis and Management of Idiosyncratic Drug-Induced Liver Injury. <em>Am J Gastroenterol</em>. 2021;116(5):878-898.", "10.14309/ajg.0000000000001259", "33929376"),
        ("European Association for the Study of the Liver. EASL Clinical Practice Guidelines: Drug-induced liver injury. <em>J Hepatol</em>. 2019;70(6):1222-1261.", "10.1016/j.jhep.2019.02.014", None),
        ("Suk KT, Kim DJ, Kim CH, et al. A prospective nationwide study of drug-induced liver injury in Korea. <em>Am J Gastroenterol</em>. 2012;107(9):1380-1387.", "10.1038/ajg.2012.138", "22733302"),
        ("Danan G, Teschke R. RUCAM in Drug and Herb Induced Liver Injury: The Update. <em>Int J Mol Sci</em>. 2016;17(1):14.", "10.3390/ijms17010014", "26712744"),
        ("LiverTox: Clinical and Research Information on Drug-Induced Liver Injury. Bethesda (MD): National Institute of Diabetes and Digestive and Kidney Diseases.", None, "31643176"),
    ],
    "svgs": [
        svg_table("DILI 패턴 분류 (R 비율)",
                  ["패턴", "R 비율", "주요 원인 약물"],
                  [["간세포성", "> 5", "Isoniazid, methotrexate, 한약"],
                   ["혼합형", "2-5", "일부 항생제, NSAIDs"],
                   ["담도성", "< 2", "Amoxicillin/clavulanate, anabolic steroid"]],
                  caption="R = (ALT/ULN) ÷ (ALP/ULN)"),
        svg_checklist("DILI 의심 시 표준 흐름",
                      ["1. 의심 약물 즉시 중단",
                       "2. 다른 원인 배제 (바이러스, 자가면역, 알코올, 영상)",
                       "3. RUCAM score로 인과관계 평가",
                       "4. 1-2주 후 ALT 재검 - 호전 확인",
                       "5. 회복 안 되면 입원·간 생검",
                       "6. 같은 약 재투여 일반적으로 금지"],
                      caption="의심 약물 중단이 가장 결정적인 단계"),
    ],
    "related": [
        ("/간수치-높음/", "건강검진 간수치(AST·ALT) 높음"),
        ("/간경변-약물-주의/", "간경변 환자가 피해야 할 약·영양제"),
        ("/간수치-종류-차이/", "AST · ALT · GGT 차이"),
    ],
})

# 05-9: PIVKA-II
ARTICLES.append({
    "slug": "PIVKA-II-간암마커",
    "h1": "PIVKA-II - 간암 종양표지자의 또 다른 축",
    "description": "PIVKA-II (DCP)의 의미, AFP와의 보완 관계, 와파린의 영향, 한국 임상에서의 사용을 정리합니다.",
    "series_slug": "간수치", "series_display": "간수치 이상", "last_crumb": "PIVKA-II",
    "section_label": "간수치", "about": "간암 종양표지자",
    "tldr": "PIVKA-II(DCP, des-γ-carboxy prothrombin)는 간암에서 분비되는 비정상 응고인자입니다. AFP가 정상인 간암 약 30-40%에서 PIVKA-II가 양성이라 <em>두 마커를 함께 봐야 검출률이 올라갑니다</em>. 와파린 복용 환자에서는 위양성 가능. 한국 KLCA-NCC는 검진·추적 모두에서 PIVKA-II를 표준으로 둡니다.",
    "sections": [
        ("PIVKA-II는 무엇인가",
         "<p>정상 응고인자 II(prothrombin)는 비타민 K 의존적 카르복실화를 거쳐 활성화됩니다. 간암 세포는 이 카르복실화가 불완전한 비정상 단백을 분비하는데, 이것이 PIVKA-II(des-γ-carboxy prothrombin, DCP)입니다.</p><ul><li>정상 범위: < 40 mAU/mL (검사실에 따라 다소 다름)</li><li>간암 의심: > 40 또는 진행성 간 질환에서 추적 변화</li><li>일본·한국에서 표준 사용, 미국·유럽은 보조</li></ul>"),
        ("AFP와의 보완 관계",
         "<p>두 종양표지자는 서로 다른 환자군을 잡습니다.</p><ul><li>AFP만 양성 - 약 30-50%</li><li>PIVKA-II만 양성 - 약 20-30%</li><li>둘 다 양성 - 약 30-40%</li><li>둘 다 음성인 간암 - 약 10-15% (영상이 결정적)</li></ul><p>두 마커를 함께 보면 단독보다 검출률이 의미 있게 올라갑니다. 한국 가이드라인은 두 마커 + 초음파 또는 CT/MRI 조합을 권장합니다.</p>"),
        ("와파린·비타민 K 결핍의 영향",
         "<p>중요한 위양성 원인입니다.</p><ul><li>와파린 복용 환자 - PIVKA-II가 매우 높게 측정됨 (간암과 무관)</li><li>비타민 K 결핍 - 만성 알코올, 흡수 장애</li><li>장기 항생제로 장내 비타민 K 합성 억제</li><li>고도 간 합성능 저하 (PT가 매우 길어진 환자)</li></ul><p>이런 환자는 PIVKA-II 해석이 어려워 AFP와 영상에 더 의존합니다.</p>"),
        ("간암 검진과 추적에서의 역할",
         "<p>한국 KLCA-NCC 가이드라인 (2022):</p><ul><li>간암 고위험군 (B/C형 간염, 간경변)에서 6개월마다 영상 + AFP + PIVKA-II</li><li>간암 치료 후 추적 - 두 마커 + 영상으로 재발 감시</li><li>치료 반응 평가 - 마커 감소 패턴이 영상 변화보다 빠를 수 있음</li></ul><p>일본·대만·한국에서 PIVKA-II가 일상적으로 쓰이는 반면, 미국 AASLD는 \"보조적\"으로 두 마커 사용을 약하게 권장합니다 - 지역별 임상 전통 차이입니다.</p>"),
        ("수치 해석의 함정",
         "<p>PIVKA-II 절대값보다 추세가 중요합니다.</p><ul><li>한 번 약간 상승 - 비특이적, 다음 추적에서 다시 평가</li><li>추적 중 점진적 상승 - 영상 적극 평가</li><li>매우 높은 값 (> 100) - 진행 간암 의심 또는 와파린 영향 확인</li><li>치료 후 급감 - 좋은 반응 신호</li><li>치료 후 다시 상승 - 재발 의심</li></ul>"),
    ],
    "faq": [
        ("PIVKA-II가 50인데 간암인가요?", "<p>약간의 상승은 비특이적일 수 있습니다. 와파린·비타민 K 평가, 영상 검사로 추가 평가합니다.</p>"),
        ("AFP가 정상인데 PIVKA-II가 높아요. 간암인가요?", "<p>PIVKA-II 단독 양성 간암이 약 20-30%이므로 적극적으로 영상 검사가 필요합니다.</p>"),
        ("와파린을 끊으면 PIVKA-II가 정상으로 돌아오나요?", "<p>네. 보통 비타민 K 보충 또는 와파린 중단 1-2주 후 회복됩니다.</p>"),
        ("PIVKA-II 검사가 보험 적용되나요?", "<p>한국에서 간암 고위험군의 정기 검진·추적에서 보험 적용됩니다.</p>"),
        ("미국에서는 안 쓴다는데 한국에서는 왜 쓰나요?", "<p>한국·일본에서 누적된 임상 데이터가 풍부해 가이드라인에 표준으로 들어가 있습니다. 임상적으로 유용성이 입증되어 사용됩니다.</p>"),
    ],
    "refs": [
        ("Korean Liver Cancer Association (KLCA), National Cancer Center (NCC). 2022 KLCA-NCC Korea Practice Guidelines for the Management of Hepatocellular Carcinoma. <em>J Liver Cancer</em>. 2023;23(1):1-120.", "10.17998/jlc.2022.11.07", None),
        ("Marrero JA, Feng Z, Wang Y, et al. Alpha-fetoprotein, des-gamma carboxyprothrombin, and lectin-bound alpha-fetoprotein in early hepatocellular carcinoma. <em>Gastroenterology</em>. 2009;137(1):110-118.", "10.1053/j.gastro.2009.04.005", "19362088"),
        ("Singal AG, Llovet JM, Yarchoan M, et al. AASLD Practice Guidance on prevention, diagnosis, and treatment of hepatocellular carcinoma. <em>Hepatology</em>. 2023;78(6):1922-1965.", "10.1097/HEP.0000000000000466", "37199193"),
        ("Liebman HA, Furie BC, Tong MJ, et al. Des-γ-carboxy (abnormal) prothrombin as a serum marker of primary hepatocellular carcinoma. <em>N Engl J Med</em>. 1984;310(22):1427-1431.", "10.1056/NEJM198405313102204", "6201741"),
    ],
    "svgs": [
        svg_table("AFP와 PIVKA-II 비교",
                  ["", "AFP", "PIVKA-II"],
                  [["정상 범위", "< 7-10 ng/mL", "< 40 mAU/mL"],
                   ["민감도 (단독)", "약 50-60%", "약 50-60%"],
                   ["함께 사용 시 민감도", colspan := "약 80-90%", ""],
                   ["위양성 원인", "임신, 활동성 간염, 일부 종양", "와파린, 비타민 K 결핍"],
                   ["한국 표준", "Yes", "Yes"]],
                  caption="두 마커 + 영상 조합이 한국 표준"),
        svg_checklist("PIVKA-II 해석 시 점검 사항",
                      ["와파린·DOAC 복용 여부",
                       "최근 항생제 복용 (비타민 K 합성 억제)",
                       "만성 알코올·흡수 장애 (비타민 K 결핍)",
                       "PT/INR 매우 긺",
                       "추세 (단일 값보다 변화)"],
                      caption="단일 값보다 환자 맥락과 추세가 중요"),
    ],
    "related": [
        ("/알파태아단백/", "AFP - 정상범위와 간암 의심 기준"),
        ("/B형간염-간암검진/", "B형간염 환자가 6개월마다 간암 검진"),
        ("/간암-재발-추적/", "간암 재발 추적 - 첫 5년의 일정"),
    ],
})

# 05-10: 간생검
ARTICLES.append({
    "slug": "간생검-언제-필요한가",
    "h1": "간생검 - 언제 필요한가",
    "description": "간생검(liver biopsy)의 적응증, 비침습 검사로 결정 못 하는 상황, 합병증·금기, 대안을 정리합니다.",
    "series_slug": "간수치", "series_display": "간수치 이상", "last_crumb": "간생검",
    "section_label": "간수치", "about": "간생검",
    "tldr": "비침습 검사(혈액·영상·Fibroscan·MRE)로 진단·평가가 끝나는 환자가 늘면서 간생검의 필요성은 줄었습니다. 그러나 <em>원인이 모호한 만성 간 질환, 약물성 간 손상 의심, 자가면역 평가, 일부 종양 진단</em>에서는 여전히 결정적입니다. 합병증 위험과 대안을 함께 봐서 결정합니다.",
    "sections": [
        ("간생검이 필요한 상황",
         "<p>현재 간생검이 우선 고려되는 적응증:</p><ul><li>비침습 검사 결과가 모호하거나 불일치</li><li>원인 모호한 만성 간 질환 (자가면역, PBC, PSC, 윌슨병 등 감별)</li><li>약물성 간 손상의 진단·중증도 평가</li><li>면역억제·이식 후 거부반응 vs 약물 부작용 감별</li><li>드물지만 일부 종양의 조직 진단 (영상으로 모호한 경우)</li><li>임상시험·연구 목적</li></ul>"),
        ("비침습 검사가 대체한 영역",
         "<p>예전에는 생검이 표준이었지만 이제 대체된 영역:</p><ul><li>지방간·MASH 평가 - FIB-4, Fibroscan, MRE, FAST score로 대부분 결정</li><li>B/C형 간염 섬유화 평가 - Fibroscan이 표준</li><li>간세포암 진단 - 영상 기준 (역동적 CT/MRI) 충족 시 생검 불필요</li></ul><p>이런 변화로 간생검 시행 건수가 지난 10-15년 사이 의미 있게 감소했습니다.</p>"),
        ("생검 방법과 위험",
         "<p>경피적 간생검의 표준 방법:</p><ul><li>초음파 가이드 - 정확한 위치 확인</li><li>국소 마취 후 생검 바늘로 약 1.5-2 cm 조직 채취</li><li>채취 후 6시간 이상 안정·관찰</li><li>당일 또는 다음 날 퇴원</li></ul><p>합병증:</p><ul><li>통증 - 약 30%에서 가벼운 우상복부 통증</li><li>출혈 - 의미 있는 출혈 0.3-0.5%, 수혈 필요한 경우 드묾</li><li>담즙 누출 - 매우 드묾</li><li>사망률 - 0.01-0.05% (매우 낮음, 대부분 대량 출혈)</li></ul>"),
        ("금기와 주의",
         "<p>다음 상황에서는 경피적 생검 회피 또는 대안 선택:</p><ul><li>심한 응고 장애 (INR > 1.5, 혈소판 < 50,000)</li><li>복수 - 천자 후 생검 또는 경경정맥 생검(transjugular)</li><li>혈관종·낭종이 의심되는 부위</li><li>협조 불가 환자</li><li>심한 비만·아주 마른 체격</li></ul><p>경경정맥 생검(transjugular)은 출혈 위험이 높은 환자에서 대안입니다.</p>"),
        ("환자가 알아둘 것",
         "<p>외래에서 자주 받는 질문 정리:</p><ul><li>\"꼭 받아야 하나\" - 비침습 평가가 충분하면 회피 가능</li><li>\"위험한가\" - 적절한 환자에서는 합병증 위험 매우 낮음</li><li>\"통증이 심한가\" - 대부분 견딜 만한 정도, 약물로 조절</li><li>\"입원이 필요한가\" - 당일 또는 1박 정도</li><li>\"결과는 언제 나오나\" - 보통 1-2주</li></ul>"),
    ],
    "faq": [
        ("MRE랑 Fibroscan으로 충분한데 왜 생검을?", "<p>두 검사가 일치하지 않거나 원인이 불분명할 때, 또는 자가면역·약물성 평가가 필요할 때 결정적입니다.</p>"),
        ("간생검 통증이 너무 무서운데?", "<p>국소마취 후 진통제로 조절합니다. 대부분 견딜 만한 수준이며 6시간 후엔 거의 사라집니다.</p>"),
        ("간이 작거나 위치가 깊으면 어렵나요?", "<p>초음파 가이드로 정확한 위치를 확인해 시행합니다. 매우 어려운 위치는 경경정맥·복강경 생검을 고려.</p>"),
        ("시술 후 며칠 쉬어야 하나요?", "<p>당일 안정 후 다음 날부터 가벼운 활동 가능. 격렬한 운동·무거운 짐 들기는 1주일 피하세요.</p>"),
        ("결과에서 \"섬유화 F2\"가 무엇을 의미하나요?", "<p>METAVIR 5단계(F0-F4)에서 중간 단계 섬유화. 진행성 단계로, 추적 강도와 치료 결정에 영향을 줍니다.</p>"),
    ],
    "refs": [
        ("Rockey DC, Caldwell SH, Goodman ZD, Nelson RC, Smith AD; American Association for the Study of Liver Diseases. Liver biopsy. <em>Hepatology</em>. 2009;49(3):1017-1044.", "10.1002/hep.22742", "19243014"),
        ("European Association for the Study of the Liver. EASL-EASD-EASO Clinical Practice Guidelines on the management of MASLD. <em>J Hepatol</em>. 2024;81(3):492-542.", "10.1016/j.jhep.2024.04.031", None),
        ("Bedossa P, Patel K. Biopsy and Noninvasive Methods to Assess Progression of Nonalcoholic Fatty Liver Disease. <em>Gastroenterology</em>. 2016;150(8):1811-1822.", "10.1053/j.gastro.2016.03.008", "27003601"),
        ("Berzigotti A, Tsochatzis E, Boursier J, et al. EASL Clinical Practice Guidelines on non-invasive tests for evaluation of liver disease severity and prognosis. <em>J Hepatol</em>. 2021;75(3):659-689.", "10.1016/j.jhep.2021.05.025", "34166721"),
    ],
    "svgs": [
        svg_table("간생검 적응증 (2025 기준)",
                  ["우선 고려", "비침습으로 대체"],
                  [["원인 모호 만성 간 질환", "지방간·MASH 평가"],
                   ["자가면역·PBC·PSC 감별", "B/C형 간염 섬유화"],
                   ["약물성 간 손상 진단", "간세포암 진단 (영상 기준 충족 시)"],
                   ["이식 후 거부반응 평가", "혈소판 정상·간기능 정상의 단순 ALT 상승"]],
                  caption="비침습 검사가 발달해 생검 적응증이 좁아짐"),
        svg_table("생검 방법별 비교",
                  ["방법", "특징", "주된 적응"],
                  [["경피적 (초음파 가이드)", "표준, 외래·1박", "일반 환자"],
                   ["경경정맥 (transjugular)", "출혈 위험 낮음", "응고 장애·복수 환자"],
                   ["복강경", "직접 시야 확인", "복강 평가 동시 필요 시"]],
                  caption="환자 상황에 따라 방법 결정"),
    ],
    "related": [
        ("/간섬유화스캔-수치/", "Fibroscan 수치 읽는 법"),
        ("/지방간-정밀검사/", "지방간 진단 후, 섬유화 정밀검사"),
        ("/약물성-간손상-DILI/", "약물·영양제·한약 - 간 손상 가능성 점검"),
    ],
})

print(f"Series 05 - building {len(ARTICLES)} articles...")
for spec in ARTICLES:
    render_article(spec)
print("Done.")
